### PR TITLE
Update_1_cr3bp_dj

### PR DESCRIPTION
**Pull request by DhruvJ22**
Updated CR3BP setup. Contains a robust single shooter and continuation scheme to compute families of Periodic Orbits. Included multiple examples to test a variety of possible combinations of setup.

### CODE REVIEW

**Comment by DhruvJ22** [comment]
I plan to debug the quality errors soon. I plan to create a new PR and push my latest work that uses OOP principles after this PR is closed.

**Comment by DhruvJ22** [comment]
@astrojuanlu and @JackCrusoe47, I am facing a quality error - "{function} is too complex" error. I would appreciate any leads to debug it without majorly restructuring the function. Thanks!

**Comment by DhruvJ22** [comment]
@astrojuanlu, check out https://github.com/DhruvJ22/Astrodynamics_Research. This is what the next update of this PR will look like. I can either push it right nown as reviewing it will be easier than the current PR, or wait for you to review the current PR. I am confident that my new setup will pass the "function too complex" quality test.

**Comment by DhruvJ22** [comment]
@JackCrusoe47 Thank you for your insight. I think I can solve the quality error with my latest formulation: https://github.com/DhruvJ22/Astrodynamics_Research

**Comment by astrojuanlu** [comment]
Hi @DhruvJ22, I'm very sorry for the huge delay - the pull request is big and it caught us at a very bad time, since both @jorgepiloto and I were ramping up new jobs.

I still don't think I will have time to review this but I am willing to merge it, therefore I will try squashing all the commits so the quality checks run again and hit the button unless I see something weird.

**Comment by astrojuanlu** [comment]
Oh yes, `po_single_shooter_cr3bp` is too complex. If you have the time to break that function down in different pieces, that would be great - for example, you can split the initialization on one side, and then the `while True` part in another.

**Comment by DhruvJ22** [comment]
@astrojuanlu Thank you for getting back to me! I have made a lot of changes and I plan to push them in the next few days.

**Comment by astrojuanlu** [comment]
Quality errors are now minor:

```
contrib/cr3bp_DhruvJ/cr3bp_model_master.py:18:1: W293 blank line contains whitespace
contrib/cr3bp_DhruvJ/cr3bp_model_master.py:126:15: E711 comparison to None should be 'if cond is None:'
contrib/cr3bp_DhruvJ/cr3bp_model_master.py:128:28: E711 comparison to None should be 'if cond is None:'
contrib/cr3bp_DhruvJ/cr3bp_lib_calc.py:3:29: W291 trailing whitespace
```

**Comment by DhruvJ22** [comment]
Whoops, I just saw your comment. I have fixed the quality errors. I hope we can merge this to the main. I would appreciate your guidance on how to test, update and add this code to the /src

**Comment by astrojuanlu** [comment]
Thanks a lot for your persistence @DhruvJ22! It would indeed be great to have this code in the library itself. I will get back to you in the coming weeks with ideas on how we can do that - basically we should slowly and gradually bring functions to `src/poliastro/threebody` as we find good validation sources for them.

**Pull request merged**
