### PR TITLE
Minor `czml` changes

### PR DESCRIPTION
**Pull request by Yash-10**
Trying to make some minor changes that I had in mind but forgot to do earlier.

I think changing `to(...).value` to `to_value(...)` in all modules, wherever they exist, might be made another issue?

### CODE REVIEW

**Comment by Yash-10** [comment]
I wonder if this could be removed?:

https://github.com/poliastro/poliastro/blob/b4ea056db0d5eede573d5bbf7d426658b1db2361/src/poliastro/czml/extract_czml.py#L543-L544

Since in `__init__` it is ensured that if the attractor passed is None, then Earth is kept as the default?

**Comment by astrojuanlu** [comment]
Sorry @Yash-10 I missed this one!

> I wonder if this could be removed?

Yeah, looks like it 👍🏽

**Comment by Yash-10** [comment]
Made that change then :+1:

**Review by astrojuanlu — APPROVED** [review]
LGTM!

**Pull request merged**
