### PR TITLE
Codecov fix

### LINKED ISSUE #206: No coverage reports
See https://travis-ci.org/poliastro/poliastro/jobs/264820443

Some CI changes broke the coverage reports around two months ago. This is the last commit with coverage:

https://codecov.io/gh/poliastro/poliastro/commit/f2823d639020b0775dfe8c6607a0052786787b01/builds

### PR DESCRIPTION
**Pull request by anhiga**
Fixed #206 by adding `--cov` argument to setup.cfg.

### CODE REVIEW

**Comment by Juanlu001** [comment]
Finally! Thanks for the fix, will merge when Travis finishes.

**Comment by anhiga** [comment]
Actually, I'm still working on it. I think that travis will pass but it won't generate any report.

**Comment by Juanlu001** [comment]
Oops, didn't see the [WIP]. Ping me when done.

**Comment by Juanlu001** [comment]
The backlog for OS X Builds is quite long https://www.traviscistatus.com/ so I suggest you not to wait for it to finish if you can avoid it...

**Comment by Juanlu001** [comment]
And BTW, isn't the codecov bot comment the proof that the report was uploaded?

**Comment by anhiga** [comment]
Yes, Travis was successful, and the report was uploaded, but Appveyor failed.

**Comment by anhiga** [comment]
I've been doing `push -f` in order to get a clearer log in poliastro, but I guess that makes PR difficult to review. Is it a good decision?

**Comment by anhiga** [comment]
@Juanlu001 It is ready to be merged, although we should wait for codecov to comment 😆

**Comment by Juanlu001** [comment]
> I've been doing `push -f` in order to get a clearer log in poliastro, but I guess that makes PR difficult to review. Is it a good decision?

It's totally acceptable, although you might want to do this as the last step, after an interactive rebase to remove dirty commits, when everything works.

**Pull request merged**
