### PR TITLE
Added favicon for docs

### LINKED ISSUE #1111: Customizing Docs Favicon
Right now there is a default favicon rendered on the [docs](https://docs.poliastro.space/en/stable/) page. We could consider rendering a customized one, similar to (or same) as displayed on the poliastro [website](https://blog.poliastro.space/).

### PR DESCRIPTION
**Pull request by Yash-10**
Fixes #1111. Added favicon for docs, same as for the poliastro website.

Thanks!

### CODE REVIEW

**Review by astrojuanlu — CHANGES_REQUESTED** [review]
Hi @Yash-10 , thanks for this addition and sorry for the long delay!

Could you please set the favicon background to white, rebase on top of `main`, and squash everything in one commit?

**Comment by Yash-10** [comment]
Hello @astrojuanlu, 

This is how the icon is seen currently:

Screenshot from 2021-03-21 15-37-55

I noticed from poliastro/poliastro.github.io#64 that we need a white background. I am slightly confused in changing the background to white. I tried converting it to a png format to be able to set the background color to white and it gives:

favicon-2 (1)

This obviously doesn't seem to be what we would want since it just made the background solid white (although I could make it transparent white).

Do you know about a good online software that could do the work?

Sorry for this, but I would try to resolve it since I am probably missing something.

Thanks!!

**Comment by astrojuanlu** [comment]
@Yash-10 Isn't it enough to turn https://github.com/poliastro/poliastro/blob/main/docs/source/logo/logo.png into a favicon? It already has white background

**Comment by Yash-10** [comment]
Oh yes, sorry, I overlooked it. Thanks!

**Comment by astrojuanlu** [comment]
Looks great! Merging, thanks @Yash-10 !

**Pull request merged**
