### PR TITLE
Frames in Orbit objects

### PR DESCRIPTION
**Pull request by Juanlu001**
This is the first step in addressing https://github.com/poliastro/poliastro/issues/434. What I did here was to create reference frames centered in each of the bodies available in poliastro that are parallel to ICRS (sort of equivalents for HCRS and GCRS for the rest of the bodies) and add a `Orbit.frame` property that can compute this frame for a given `Orbit`. If the attractor is a custom body, for the moment it will raise an error.

Missing:

* [x] Validation of reference frame transformations themselves.
* [x] Proper frame in `Orbit.sample`.
* [x] Documentation.

Some notes:

* For orbits coming from ephemerides, it will set them to ICRS, so no changes on the Moon until we have a transform method.
* We still don't need to touch propagation, since we cannot set a custom frame using the public API.
* I realized that flake8 has a lot to complain about poliastro. Those fixes will go in a separate pull request to not clutter this one and help reviewers.
* I was hesitating whether to touch the `BaseState` code, but in the end I didn't because of https://github.com/poliastro/poliastro/issues/370.
* We had to do the work ourselves because of https://github.com/astropy/astropy/issues/7770.

### CODE REVIEW

**Comment by Juanlu001** [comment]
I suspect the base report is missing because of recent Codecov incidences: https://status.codecov.io/incidents/t9tlhn0pfxl1

**Comment by Juanlu001** [comment]
Coverage publishing failed:

https://circleci.com/gh/poliastro/poliastro/526

> Error: HTTP 400
Unable to locate build via CircleCI API. Please upload with the Codecov repository upload token to resolve issue.

**Comment by Juanlu001** [comment]
The testing code is affected by the changes in `sample`, since we were using that to plot trajectories. I think the safest thing for now is to keep accepting a `BaseRepresentation` and give a warning.

**Comment by Juanlu001** [comment]
I've been waiting for so long to have this, so I'm merging! :rocket:

**Comment by hrishikeshgoyal** [comment]
Does this make sense to attache a new reference frame to `Orbit` in addition to the existing `self._frame` that can act as a communicating frame? 
For example if user needs to create an orbit using ephemerides given in some frame(say foo) other than the frame(say bar) parallel to ICRS centred at attractor and subsequently needs to call propagate. In that case following can be a sequence of steps to follow:
a. Take user inputs in foo
b. Transform inputs given in foo to bar
c. Create the orbit in the frame bar.
c. Perform all required operations in frame bar (e.g propagate). It might also require to transform (i.e. from foo to bar) the parameters passed to the operation.
d. Transform the output of the operations performed in the frame bar to foo.
e. Output the results in foo to user.

**Comment by Juanlu001** [comment]
Answered in https://github.com/poliastro/poliastro/issues/434#issuecomment-455673516

**Pull request merged**
