### PR TITLE
DOC: fix docstring for hyperbolic to mean anomaly

### PR DESCRIPTION
**Pull request by sairevanth0007**
Made the changes specified in issue #1601 

----
:books: Documentation preview :books:: https://poliastro--1608.org.readthedocs.build/en/1608/

### CODE REVIEW

**Review by jorgepiloto — APPROVED** [review]
Thanks for fixing this, @sairevanth0007.

**Comment by sairevanth0007** [comment]
> Thanks for fixing this, @sairevanth0007.

Welcome @jorgepiloto . I would like to contribute more to open-source projects and solve issues. Could you please suggest some resources or something like that from where I can learn more and solve bigger issues if you don't mind.

**Comment by jorgepiloto** [comment]
There are some basic requirements you need to have to start contributing to open-source:

* Discipline. It takes a bit to learn all the tools. It may be frustrating at first but with effort and some help from the community everyone succeeds. Join the poliastro channel in http://chat.poliastro.space/.

* Know the software you want to contribute to. It is very difficult to help mantaining a project unless you know how to use it, how it is structured, what tools is it built with... This is the reason behind the gallery of tutorials. Take your time to explore all the example in https://docs.poliastro.space/en/stable/gallery.html.

* Start with the `good first issues`. Some of those may be boring but they will force you to practice tools like `git`, which is basic for any modern software project.

* The poliastro project requires astrodynamics and orbital mechanics knowledge if you want to contribute to the `core/` sub-package. For a collection of materials used in this project, see https://docs.poliastro.space/en/stable/bibliography.html

**Comment by sairevanth0007** [comment]
Thank you :) @jorgepiloto . I will try and look into the things mentioned.

**Pull request merged**
