### PR TITLE
Theme Changed to Alabaster!

### PR DESCRIPTION
**Pull request by shreyasbapat**
- [x] Mobile Compatibilty
- [x] Solving Documentation Issues
- [x] Issue in favicon.ico

### CODE REVIEW

**Comment by shreyasbapat** [comment]
https://poliastro-sh.readthedocs.io/en/doc-theme-change/
Mobile Compatibile now :)

**Comment by Juanlu001** [comment]
I see that you "temporarily" removed the favicon. What are your plans there? What's the status of this in general?

**Comment by shreyasbapat** [comment]
I will add it in another PR. This is mergeable😅

**Comment by shreyasbapat** [comment]
I have to see and inspect which mime type is supported in sphinx

**Comment by shreyasbapat** [comment]
Any particular customisation you have in mind?

**Comment by shreyasbapat** [comment]
Do we see some future of this pull request?

**Comment by Juanlu001** [comment]
> it's too much of a change at the moment, and as I said I first want to understand the problem between Read the Docs, Plotly, jQuery, require.js... :disappointed:

**Comment by shreyasbapat** [comment]
Yep. Let's wait for that to resolve first!

**Pull request closed without merging**
