### PR TITLE
Updated Porkchop plot with Matplotlib 3.4.0

### PR DESCRIPTION
**Pull request by DhruvSondhi**
Hello,
This PR aims to fix the `py38-images` test (via #1142)
The tests are passing :)
```python
tests/tests_plotting/test_misc.py::test_plot_inner_solar_system_static PASSED                                                   [  8%]
tests/tests_plotting/test_misc.py::test_plot_outer_solar_system_static PASSED                                                   [ 16%]
tests/tests_plotting/test_porkchop.py::test_porkchop_plotting PASSED                                                            [ 25%]
tests/tests_plotting/test_static.py::test_basic_plotting PASSED                                                                 [ 33%]
tests/tests_plotting/test_static.py::test_basic_trajectory_plotting PASSED                                                      [ 41%]
tests/tests_plotting/test_static.py::test_basic_orbit_and_trajectory_plotting PASSED                                            [ 50%]
tests/tests_plotting/test_static.py::test_trail_plotting PASSED                                                                 [ 58%]
tests/tests_plotting/test_static.py::test_plot_different_planes PASSED                                                          [ 66%]
tests/tests_plotting/test_static.py::test_body_plotting PASSED                                                                  [ 75%]
tests/tests_plotting/test_static.py::test_plot_ephem_epoch SKIPPED (need --remote-data option to run)                           [ 83%]
tests/tests_plotting/test_static.py::test_plot_ephem_no_epoch SKIPPED (need --remote-data option to run)                        [ 91%]
tests/tests_plotting/test_tisserand.py::test_tisserand_plotting PASSED                                                          [100%]

```
Thanks :)

### CODE REVIEW

**Comment by DhruvSondhi** [comment]
Image generated does have some formatting issues but as mentioned, it passes the tests with the updated `Matplotlib` versions :)
test_porkchop_plotting

**Comment by DhruvSondhi** [comment]
Hello @astrojuanlu, This fixes the tests :) ... Let's fix it at **_God's Speed_** 🚀

**Comment by astrojuanlu** [comment]
https://user-images.githubusercontent.com/316517/112987960-93a84380-9163-11eb-869e-5b1be1fbbf59.mp4

**Comment by astrojuanlu** [comment]
ezgif com-gif-maker

The differences were not due to typography issues, but label placement. Nothing to worry about, but this is the right thing to do 👍🏽

**Comment by astrojuanlu** [comment]
Thanks @DhruvSondhi !

**Pull request merged**
