### PR TITLE
Fixed atmospheric_drag API change

### PR DESCRIPTION
**Pull request by priyanshurohilla**
Addresses #935 
Plz review

### CODE REVIEW

**Comment by wumpus** [comment]
I was happy to make the change :-D but I admire your enthusiasm! In addition to the test failures, there is a notebook in the examples that is affected... it's inserted into the documentation.

**Comment by priyanshurohilla** [comment]
I know the tests will fail, here it is showing `syntax error` and i am unable to determine why is it saying so? Any comments @astrojuanlu @wumpus

**Comment by priyanshurohilla** [comment]
> I was happy to make the change :-D but I admire your enthusiasm! In addition to the test failures, there is a notebook in the examples that is affected... it's inserted into the documentation.

Thanks for the appreciation @wumpus . I will make the changes in the documentation too. Once i am done with the code changes

**Comment by wumpus** [comment]
if you keep clicking into the test failure report you'll find this error
```
check run-test: commands[0] | flake8 src tests
tests/tests_twobody/test_perturbations.py:294:9: E999 SyntaxError: invalid syntax
```

Does that help you? The error is the end of the line before.

BTW you can run this test before you check in.

**Comment by priyanshurohilla** [comment]
Yes I know what's failing!! But why exactly is it failing? I mean to say I don't know why is it producing syntax error!!

**Comment by wumpus** [comment]
You added a line without a comma.

**Comment by priyanshurohilla** [comment]
What the hell, how can I do this🥺

**Comment by wumpus** [comment]
... now it's failing for the reason I pointed out at the top ...

**Comment by priyanshurohilla** [comment]
> ... now it's failing for the reason I pointed out at the top ...

Yes i know @wumpus i am 

> ... now it's failing for the reason I pointed out at the top ...

Yes i know that.. i was just getting sure about the correctness of the code. Also the `tox -e docs` is not working on my pc thats why checking the docs code by pushing it.
Also while working on it i realised for `radiation_pressure` `A_over_m` can also be applied. So i have done that also.
Once tests are passed, I'll squash all the commits into one.

**Comment by astrojuanlu** [comment]
Echoing what @wumpus said thanks for your enthusiasm @priyanshurohilla - I would recommend you to run at least `tox -e reformat && tox -e check` before pushing, and `tox -e py38-fast` for extra security.

This has a conflict with `Natural and artificial perturbations.ipynb`, which is probably going to be very difficult to fix manually. Perhaps it's better to start from current `poliastro/master` for simplicity?

**Comment by priyanshurohilla** [comment]
> Echoing what @wumpus said thanks for your enthusiasm @priyanshurohilla - I would recommend you to run at least `tox -e reformat && tox -e check` before pushing, and `tox -e py38-fast` for extra security.
> 
> This has a conflict with `Natural and artificial perturbations.ipynb`, which is probably going to be very difficult to fix manually. Perhaps it's better to start from current `poliastro/master` for simplicity?

i always check the code using`check` and `reformat` when no error comes, then only i push it .. From now onwards i'll execute `tox -e py38-fast `too. I'll start from scratch @astrojaunalu then

**Pull request closed without merging**
