### PR TITLE
Fix Jacchia equations, take 2

### PR DESCRIPTION
**Pull request by astrojuanlu**
Supersedes https://github.com/poliastro/poliastro/pull/1351 (thanks @tommasopino!), fixes https://github.com/poliastro/poliastro/issues/1509. Thanks @Nosudrum for the analysis.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
`test_jacchia77` and others are failing :x: due to a coding error on my side, fixing

**Comment by astrojuanlu** [comment]
Now units in tests are correct (I think!) but we are still getting test failures.

**Comment by Nosudrum** [comment]
Question : why does the list for each altitude in the solutions dictionary introduced here
https://github.com/poliastro/poliastro/blob/968ac2c2b3050caabb1ef02ba5841029c96dd6aa/tests/tests_earth/tests_atmosphere/test_jacchia77.py#L8-L207

have 11 items while the array of solutions [here](https://git.mysmce.com/ccmc-share/modelwebarchive/-/raw/main/Jacchi-Reference-Atmosphere/t1000.out) only has 9 ?

**Comment by Nosudrum** [comment]
Alright, I've looked over the tests and have a few questions to help me understand better how everything works :
- What's the difference between `*(u.m)**-3` and `<<(u.m**-3)` ?
- How does the new density look ? With $R$ in `kg/kmol` mixed with $M$ in `kg/mol` in the formula I am curious.
- How does the test handle different units ? The expected molecular mass is in `kg/kmol` while the computed one is in `kg/mol`.

**Comment by astrojuanlu** [comment]
> What's the difference between *(u.m)**-3 and <<(u.m**-3) ?

They're the same, but `<< (u.m**-3)` is more efficient and easier to read.

> How does the new density look?

I would expect the density to have units of `kg / m**3` (in fact, it had super weird units before, perhaps because it was molecular density?)

> How does the test handle different units ? The expected molecular mass is in kg/kmol while the computed one is in kg/mol.

Transparently:

```
In [1]: from astropy.tests.helper import assert_quantity_allclose

In [2]: from astropy import units as u

In [3]: assert_quantity_allclose(1 << u.m, 100 << u.cm)

In [4]: assert_quantity_allclose(1 << u.m, 100.0001 << u.cm)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Input In [4], in <module>
----> 1 assert_quantity_allclose(1 << u.m, 100.0001 << u.cm)

File ~/Projects/LSF/poliastro/library/.venv/lib/python3.10/site-packages/astropy/tests/helper.py:460, in assert_quantity_allclose(actual, desired, rtol, atol, **kwargs)
    458 import numpy as np
    459 from astropy.units.quantity import _unquantify_allclose_arguments
--> 460 np.testing.assert_allclose(*_unquantify_allclose_arguments(
    461     actual, desired, rtol, atol), **kwargs)

    [... skipping hidden 1 frame]

File ~/Projects/LSF/poliastro/library/.venv/lib/python3.10/site-packages/numpy/testing/_private/utils.py:844, in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf)
    840         err_msg += '\n' + '\n'.join(remarks)
    841         msg = build_err_msg([ox, oy], err_msg,
    842                             verbose=verbose, header=header,
    843                             names=('x', 'y'), precision=precision)
--> 844         raise AssertionError(msg)
    845 except ValueError:
    846     import traceback

AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 1.e-06
Max relative difference: 9.99999e-07
 x: array(1.)
 y: array(1.000001
```

**Comment by Nosudrum** [comment]
Alright, I might have figured out the issue with the density.

First of all, we are not supposed to apply equation (42) of COESA76, which is based on perfect gases. Instead, we should apply the method @jorgepiloto mentioned in https://github.com/poliastro/poliastro/pull/1351#issuecomment-948314867, which is in page 51 of the Jacchia PDF [here](https://ui.adsabs.harvard.edu/link_gateway/1977SAOSR.375.....J/ADS_PDF).

This method to compute the density is

$$\rho = \dfrac{\sum M_{i}n_{i}}{N_{A}}$$

where $M_{i}$ and $n_{i}$ are the molar mass and number density of each atmospheric component (*N2*, *O2*, *O*, *Ar*, *He*, *H*) and $N_{A}$ is Avogadro's number : $N_{A}=6.02217\times 10^{23}$ (from page 51 of the PDF as well).

Unit-wise, the molar masses $M_{i}$ are in `g/mol`, or ideally in `kg/mol`, the number densities $n_{i}$ are in `1/m3` and Avogadro's number is in `1/mol`, leading to a density in `g/m3` or `kg/m3`.

We can find the molar masses of these six atmospheric components used by Jacchia here :
https://github.com/poliastro/poliastro/blob/968ac2c2b3050caabb1ef02ba5841029c96dd6aa/src/poliastro/core/earth_atmosphere/jacchia.py#L31-L36

I've implemented this method with data from Table 10 of Jacchia (**watch out some values for the density in the data of the tests are not correct**) and the current `Jacchia77` model from `main` to compute the number densities at each altitude (which already pass the tests).

```python
import numpy as np
from astropy import units as u
from poliastro.earth.atmosphere.jacchia import Jacchia77

wmN2 = 28.0134 * u.g / u.mol
wmO2 = 31.9988 * u.g / u.mol
wmO = 15.9994 * u.g / u.mol
wmAr = 39.948 * u.g / u.mol
wmHe = 4.0026 * u.g / u.mol
wmH = 1.0079 * u.g / u.mol

Na = 6.02217e23 * 1 / u.mol  # from Jacchia PDF page 51

jacchia77_solutions = {
    90 * u.km: -5.465,
    100 * u.km: -6.247,
    120 * u.km: -7.646,
    150 * u.km: -8.701,
    200 * u.km: -9.566,
    300 * u.km: -10.667,
    400 * u.km: -11.507,
    500 * u.km: -12.246,
    560 * u.km: -12.659,
    800 * u.km: -13.991,
    1000 * u.km: -14.547,
    1500 * u.km: -15.260,
    2000 * u.km: -15.780,
    2400 * u.km: -16.085
}

for z in jacchia77_solutions:
    expected_rho_log = jacchia77_solutions[z]

    atmosphere = Jacchia77(1000 * u.K)

    properties = atmosphere.altitude_profile(z)
    for i in range(2, len(properties) - 1):
        if properties[i].value <= 1.26e-10:
            properties[i] = -9.9 * properties[i].unit
    Z, T, CN2, CO2, CO, CAr, CHe, CH, CM, WM = properties

    density = ((wmN2 * CN2 + wmO2 * CO2 + wmO * CO + wmAr * CAr + wmHe * CHe + wmH * CH) / Na).to(u.kg / u.m ** 3)
    rho_log = np.log10(density.value)

    print(
        f'altitude: {z}, expected log density: {expected_rho_log}, computed log density: {rho_log}, log difference: {(rho_log - expected_rho_log):e}')

```

The output of that code confirms this method is correct :

```
altitude: 90.0 km, expected log density: -5.465, computed log density: -5.465319893583659, log difference: -3.198936e-04
altitude: 100.0 km, expected log density: -6.247, computed log density: -6.246713709497736, log difference: 2.862905e-04
altitude: 120.0 km, expected log density: -7.646, computed log density: -7.646631488172765, log difference: -6.314882e-04
altitude: 150.0 km, expected log density: -8.701, computed log density: -8.701055108559475, log difference: -5.510856e-05
altitude: 200.0 km, expected log density: -9.566, computed log density: -9.56646463656931, log difference: -4.646366e-04
altitude: 300.0 km, expected log density: -10.667, computed log density: -10.666776795192115, log difference: 2.232048e-04
altitude: 400.0 km, expected log density: -11.507, computed log density: -11.5074807458623, log difference: -4.807459e-04
altitude: 500.0 km, expected log density: -12.246, computed log density: -12.245928150578601, log difference: 7.184942e-05
altitude: 560.0 km, expected log density: -12.659, computed log density: -12.658860298929254, log difference: 1.397011e-04
altitude: 800.0 km, expected log density: -13.991, computed log density: -13.991271789920654, log difference: -2.717899e-04
altitude: 1000.0 km, expected log density: -14.547, computed log density: -14.547404854659208, log difference: -4.048547e-04
altitude: 1500.0 km, expected log density: -15.26, computed log density: -15.260118476675942, log difference: -1.184767e-04
```

So, now onto my recommended actions :
- Update the density computation *again* to use this method. The molar masses constants may be copied directly from the code of `poliastro.core.earth_atmosphere.jacchia` or imported from there somehow. Avogadro's number can be added as a constant, or computed with $R/k$, with $R$ the perfect gas constant and $k$ Boltzmann's constant, both of which are already in `poliastro.earth.atmosphere.jacchia`. The former is preferable in my opinion, so it can be the same value as the one used by Jacchia.
- Update the jacchia solutions in the tests with data in Table 10 of the Jacchia PDF. I have used the same rows but only for the density value, so feel free to just update that one (item 10, the last one, for each altitude).

**Comment by astrojuanlu** [comment]
I _think_ I have fixed everything! Thanks again @Nosudrum for the analysis. Funny how @jorgepiloto got it right nine months ago but we haven't had time to properly do this...

It hurt a bit changing this code because it's not really well written, at some point we'll have to do a serious refactor. But at least now I _think_ everything is working. Could you please give it a try before I go and merge the PR?

**Comment by astrojuanlu** [comment]
I confirm that the current test failures are unrelated, we will study them separately in #1512.

**Comment by Nosudrum** [comment]
Yep, can confirm that density and R units are now correct 👍

**Comment by astrojuanlu** [comment]
I carefully checked that the errors are not due to this PR. Since `main` is broken anyway, let's merge this and devote our attention to #1512.

**Pull request merged**
