### PR TITLE
"Going to Mars with Poliastro" warning added

### PR DESCRIPTION
**Pull request by AunSiro**
If you had not downloaded the ephemeris and run the notebook
sequentially, you might encounter problems, as I found in #120 

I just added a small warning so you know that you might need to restart the kernel.

### CODE REVIEW

**Comment by Juanlu001** [comment]
Thanks for the pull request @AunSiro! The error that you noticed is actually a duplicate of https://github.com/poliastro/poliastro/issues/147 and https://github.com/poliastro/poliastro/issues/128, and should be fixed since https://github.com/poliastro/poliastro/pull/148. Would you check if this still happens to you with latest `master`?

**Comment by Juanlu001** [comment]
By the way, the failures are related to AWS outage yesterday.

**Comment by AunSiro** [comment]
It happened with the latest Poliastro that conda installs (intalled it yesterday). How can I check if it is up-to-date with master? if it isn't, how can I manually update it?

**Comment by Juanlu001** [comment]
The development version is already ahead from the latest released version, which is 0.6.0. You can check that here:

https://github.com/poliastro/poliastro/compare/0.6.x...master

To install the latest development version, I think this should work:

```
$ pip install git+git://github.com/poliastro/poliastro
```

provided that you have git properly configured on your computer. Otherwise, you could also try this:

```
$ pip install https://github.com/poliastro/poliastro/archive/master.zip
```

**Comment by AunSiro** [comment]
You were right, with  poliastro 0.7. the notebook downloads and uses the ephemeris without any problem. Should I cancel the pull request, or change the warning to add that it applies to anterior versions?

**Comment by Juanlu001** [comment]
We can close this pull request, since the warning will only apply to master, where it is not needed. I guess this problem is affecting many people so I might release a 0.6.1 with a proper fix. Thanks anyway for the effort :)

**Pull request closed without merging**
