### PR TITLE
Nbsphinx added

### PR DESCRIPTION
**Pull request by anhiga**
The problem here is that .ipynb files in examples folder cannot be directly linked from rst files.
As stated in the last comment of [this nbsphinx PR](https://github.com/spatialaudio/nbsphinx/pull/33), there are three options to solve this:

- Moving examples/ to docs/source/examples/. 
- Creating a symbolic link: not sure if it would works on windows, linux and macOS.
- Moving conf.py to the main directory: it would create a mess with relative paths, and undesired files.

I have chosen the first option, however any of them can be discussed on this PR.

Related to #157

### CODE REVIEW

**Comment by Juanlu001** [comment]
Thanks for working on this! I have never used nbsphinx so I will review the pull request closely. If you are still working on it please put `[WIP]` in the title of the PR, otherwise say it's ready for review and I will look closely.

**Comment by anhiga** [comment]
It seems to be an error in CI regarding one of nbsphinx dependencies, so I'll work on it, but the rest of the code can be reviewed.

**Comment by anhiga** [comment]
I have just realize that only opening .ipybn files in jupyter seems to produce a lot of little changes, but most of them are not relevant in this PR, so I can try opening another PR without so many changes if you want.

**Comment by Juanlu001** [comment]
> I have just realize that only opening .ipybn files in jupyter seems to produce a lot of little changes, but most of them are not relevant in this PR, so I can try opening another PR without so many changes if you want.

You are right. I think we can ignore them and leave the PR as it is, but I appreciate that you noticed that :grin:

**Comment by Juanlu001** [comment]
Also related to #120.

**Comment by Juanlu001** [comment]
Let's see how this goes in Read the Docs! :rocket:

**Comment by Juanlu001** [comment]
Oops, it failed:

http://readthedocs.org/projects/poliastro/builds/5507503/

Debugging RTD is as painful as doing so with any other CI service. I recommend you to set up a test RTD proyect yourself and link it to your PR branch so you can track if everything is going correctly. That should go in a separate PR though.

**Comment by Juanlu001** [comment]
Fixed by #181.

**Pull request merged**
