### PR TITLE
Build API docs with sphinx-autoapi

### PR DESCRIPTION
**Pull request by jorgepiloto**
Solves for #967 by making use of `sphinx-autoapi` for building project's API documentation. Although very useful, some warnings were raise, which is treated as an error by `tox -e docs`. Some of this warnings are related with typos and therefore, easy to fix. However, others are related with imports and I am not sure why `sphinx-autoapi` is not able to properly parse those poliastro objects.

I deleted the whole `docs/source/api` directory since it only contained `*.rst` files with the minimum required layout for building pages documentation, that is the reason behind so many simplified lines of code. By default `sphinx-autoapi` builds a temporary directory called `autoapi` inside `docs/source` and generates all necessary `*.rst`files. After desired output files (*.html, *.tex, etc...) are built, the `autoapi` folder is deleted.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Thanks a lot for this @jorgepiloto! Let me have a look locally

**Comment by jorgepiloto** [comment]
Some warnings might be the following:

In `poliastro.constants.general.py`, some planets mass are taken directly from the `astropy` package as seen in the following permalink:

https://github.com/poliastro/poliastro/blob/d40700de75b4c4269b6ef738f8970c381de122fe/src/poliastro/constants/general.py#L31

Then, they are added to the `__all__` attribute of the module:

https://github.com/poliastro/poliastro/blob/d40700de75b4c4269b6ef738f8970c381de122fe/src/poliastro/constants/general.py#L48-L50

I think this is causing the error, since they are not directly defined within the source code. The `sphinx-autopi` tries to look for `astropy/` in the `src/` directory to retrieve proper definition but, of course, it is not able to find the package because of is dependency nature.

**Comment by astrojuanlu** [comment]
In the CI we have `sphinx.errors.SphinxWarning: Cannot resolve import of poliastro.frames.equatorial.GCRS in poliastro.frames.ecliptic`, and locally I see `sphinx.errors.SphinxWarning: Cannot resolve import of poliastro.constants.general.M_earth in poliastro.constants`. :thinking:

**Comment by astrojuanlu** [comment]
Source of the warning: https://github.com/readthedocs/sphinx-autoapi/blob/6fa5cb941d01f2e0e38da01f11e709242ae5b99c/autoapi/mappers/python/mapper.py#L142-L146

**Comment by jorgepiloto** [comment]
From [official documentation](https://sphinx-autoapi.readthedocs.io/en/latest/maintenance/design.html#python):

> Anything that is imported into a module is not documented. Usually a module is where implementations exist. Therefore an import of something is usually for the usage of the implementation, and not as something to be accessed publicly.

**Comment by jorgepiloto** [comment]
I found a little hack. If the following line:

https://github.com/poliastro/poliastro/blob/d40700de75b4c4269b6ef738f8970c381de122fe/src/poliastro/constants/general.py#L31

is substituted by:

```python
from astropy.constants.iau2015 import M_earth as _M_earth, M_jup as _M_jupiter, M_sun as _M_sun

# Custom variable definition
M_earth = _M_earth
M_jupiter = _M_jupiter
M_sun = _M_sun
```

Autoapi does not complain, since these vars have been defined in the module.

**Comment by astrojuanlu** [comment]
Haha, interesting! Let's proceed like that for the moment so we don't get blocked. Please implement the hack leaving a comment, and if the docs look good we can merge.
GitHub <notifications@github.com> wrote:
“I found a little hack. If the following line:

https://github.com/poliastro/poliastro/blob/d40700de75b4c4269b6ef738f8970c381de122fe/src/poliastro/constants/general.py#L31

is substituted by:

from astropy.constants.iau2015 import M_earth as _M_earth, M_jup as _M_jupiter, M_sun as _M_sun

# Custom variable definition
M_earth = _M_earth
M_jupiter = _M_jupiter
M_sun = _M_sunAutoapi does not complain, since these vars have been defined in the module.”

**Comment by jorgepiloto** [comment]
Although the `cannot import...` warnings were fixed with previous hack, there are still some others related to duplicated docstrings or definitions... :sweat:

**Comment by astrojuanlu** [comment]
Beware of typos :wink: 

https://github.com/poliastro/poliastro/blob/d40700de75b4c4269b6ef738f8970c381de122fe/src/poliastro/earth/atmosphere/base.py#L45

**Comment by astrojuanlu** [comment]
I showed this PR to @humitos who helped me a lot understand what was going on (thanks!).

For the `sphinx.errors.SphinxWarning: Cannot resolve import of ...` warnings, it's likely because sphinx-autoapi performs static analysis to extract the documentation, and those variables are not defined there.

Options:

1. The hack that @jorgepiloto implemented (ugh :innocent:)
2. Excluding the problematic modules (using "exclude patterns") and document those manually
3. Try a different solution, for example https://github.com/sphinx-contrib/apidoc (see discussion about [`sphinx-apidoc`](https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html) on Read the Docs at https://github.com/readthedocs/readthedocs.org/issues/1139 and https://github.com/readthedocs/readthedocs.org/issues/7162)

I think option (2) is the best, given that we already started the effort of using sphinx-apidoc. We can always resort to (3) if all else fails.

Apart from that, I see that we're getting several warnings:

```
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1000/docs/source/autoapi/poliastro/core/propagation/index.rst:35: WARNING: duplicate object description of poliastro.core.propagation.farnocchia, other instance in autoapi/poliastro/core/propagation/farnocchia/index, use :noindex: for one of them
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1000/docs/source/autoapi/poliastro/czml/extract_czml/index.rst:69: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1000/docs/source/autoapi/poliastro/czml/extract_czml/index.rst:70: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1000/docs/source/autoapi/poliastro/earth/atmosphere/base/index.rst:59: WARNING: Unexpected section title.

Paramters
---------
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1000/docs/source/autoapi/poliastro/earth/index.rst:166: WARNING: Unexpected section title.

Returns
-------
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1000/docs/source/autoapi/poliastro/earth/index.rst:171: WARNING: Unexpected section title.

Notes
-----
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1000/docs/source/autoapi/poliastro/earth/index.rst:175: WARNING: Literal block expected; none found.
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1000/docs/source/autoapi/poliastro/spacecraft/index.rst:51: WARNING: Unexpected section title.

Returns
-------
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1000/docs/source/autoapi/poliastro/spacecraft/index.rst:56: WARNING: Unexpected section title.

Notes
-----
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1000/docs/source/autoapi/poliastro/spacecraft/index.rst:60: WARNING: Literal block expected; none found.
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1000/docs/source/autoapi/poliastro/twobody/thrust/index.rst:34: WARNING: duplicate object description of poliastro.twobody.thrust.change_a_inc, other instance in autoapi/poliastro/twobody/thrust/change_a_inc/index, use :noindex: for one of them
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1000/docs/source/autoapi/poliastro/twobody/thrust/index.rst:64: WARNING: duplicate object description of poliastro.twobody.thrust.change_argp, other instance in autoapi/poliastro/twobody/thrust/change_argp/index, use :noindex: for one of them
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1000/docs/source/autoapi/poliastro/twobody/thrust/index.rst:74: WARNING: duplicate object description of poliastro.twobody.thrust.change_ecc_quasioptimal, other instance in autoapi/poliastro/twobody/thrust/change_ecc_quasioptimal/index, use :noindex: for one of them
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1000/docs/source/autoapi/poliastro/twobody/thrust/index.rst:88: WARNING: duplicate object description of poliastro.twobody.thrust.change_inc_ecc, other instance in autoapi/poliastro/twobody/thrust/change_inc_ecc/index, use :noindex: for one of them
```

**Comment by jorgepiloto** [comment]
I also noticed is possible to generate docstrings for constants by doing:

```python
UNITY = 1.00
""" Unitary constant """
```

Might trigger the `sphinx-autopi` and, therefore, get rid of some warnings.

**Comment by jorgepiloto** [comment]
I was able locally to get ride of some warnings and end up having only those ones claiming for the addition of `:noindex` and `more than one target found...`. Still working on this and taking a look to previously reported suggestions :rocket:

**Comment by jorgepiloto** [comment]
OMG: I solved it in an easy way! Let me rewrite git history and push changes :+1:

**Comment by astrojuanlu** [comment]
Wohoo amazing! Looking forward to the finished version :)

**Pull request merged**
