### PR TITLE
Created codemeta.json file

### PR DESCRIPTION
**Pull request by AlphaVictorDelta**
Added 'codemeta.json' file. 
solves issue #1156

### CODE REVIEW

**Comment by AlphaVictorDelta** [comment]
Okay, @astrojuanlu. I will see what I can do.

**Review by astrojuanlu — COMMENTED** [review]
This looks better! Can you please squash these two commits into one? And also, validate `codemeta.json` with https://github.com/caltechlibrary/convert_codemeta (please paste the output here)

**Comment by AlphaVictorDelta** [comment]
Screenshot (5)

**Review by astrojuanlu — APPROVED** [review]
Hi @AlphaVictorDelta, this looks very good! Thanks for this pull request 🚀 If we want any changes, we can figure them out along the way. I'm merging this.

**Pull request merged**
