### PR TITLE
Update jacchia.py R gas constant unit 

### PR DESCRIPTION
**Pull request by TommasoPino**
correction of R gas constant dimension unit.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Woops, this is pretty bad, thanks a lot @TommasoPino ! However, it looks like this test is failing:

https://github.com/poliastro/poliastro/blob/68bfb05542589a998a46718146db9c981b4e2f3e/tests/tests_earth/tests_atmosphere/test_jacchia77.py#L259-L267

Requesting a review from @jorgepiloto

**Comment by jorgepiloto** [comment]
Thanks for pinging @astrojuanlu. I ran out of time yesterday while reviewing the effects of this single line of code. 

The quantity `R` is only used for computing the density, which I see its being computed using equation (42) from COESA model, see:

Coesa76 density             |  Jacchia77 density
:-------------------------:|:-------------------------:
  |  

Notice that the only difference be tween the two methods is that Jacchia77 divides by Avogadro's constant. I think this comes from the definition of `R_g = R_u / M_g` maybe, not sure why... Anyway, the problem seems to be related with those definitions.

**Comment by astrojuanlu** [comment]
I see! @TommasoPino does that make sense? Would you change your pull request to add a meaningful code comment instead?

**Comment by astrojuanlu** [comment]
@nosudrum analyzed this issue a bit more in #1509

**Comment by Nosudrum** [comment]
I have analysed this in depth in #1509 [here](https://github.com/poliastro/poliastro/issues/1509#issuecomment-1141130732). Hopefully my conclusions are correct and can help fix this :)

**Comment by astrojuanlu** [comment]
I added @TommasoPino commit to #1511 and included the changes @Nosudrum suggested in #1509, so let's continue the conversation there.

**Comment by astrojuanlu** [comment]
The units problem is now fixed 🎉

**Pull request closed without merging**
