### PR TITLE
Optimized orbit.propagate()

### PR DESCRIPTION
**Pull request by priyanshurohilla**
Addresses #815 
Please review the changes

### CODE REVIEW

**Comment by priyanshurohilla** [comment]
Why are the tests failing?

**Comment by astrojuanlu** [comment]
> Why are the tests failing?

I didn't look at the tests, but you changed the return value of a function that is used everywhere :)

**Comment by priyanshurohilla** [comment]
> > Why are the tests failing?
> 
> I didn't look at the tests, but you changed the return value of a function that is used everywhere
Oh godd this didn't click to me!! I need to see what else I can do

**Comment by astrojuanlu** [comment]
I expressed my dislike of changing the return value according to a parameter and also the original use case is covered with existing functions reusing the Astropy objects, so let's close this. Thanks @priyanshurohilla for the effort nonetheless!

**Pull request closed without merging**
