### PR TITLE
DOC: parse notebooks with MyST-NB

### PR DESCRIPTION
**Pull request by mgeier**
This is another experiment, see #1260.

Again, I'm not sure whether that works, and it might need a few iterations with RTD.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Oh wow, it failed because of pip trying to resolve some dependencies... I would love to see the continuation of this experiment. I can lend a hand tomorrow.

**Comment by astrojuanlu** [comment]
I waited 90 minutes locally, then both ran out of patience and saw the response to pypa/pip#10092 :) So, this is the culprit:

```
$ pip check
sphinx-rtd-theme 0.5.2 has requirement docutils<0.17, but you have docutils 0.17.1.
myst-nb 0.12.3 has requirement myst-parser~=0.13.5, but you have myst-parser 0.15.1.
myst-nb 0.12.3 has requirement nbconvert~=5.6, but you have nbconvert 6.1.0.
```

According to https://github.com/executablebooks/MyST-NB/issues/333#issuecomment-855382132,

> You can already use myst-nb==0.13.0a1 and yes we will be releasing myst-nb 0.13 "proper" shortly :crossed_fingers:

And, indeed, with that change the installation succeeds locally.

**Comment by astrojuanlu** [comment]
```
Extension error:
source_suffix '.ipynb' is already registered
```

**Comment by mgeier** [comment]
Thanks for fixing the previous error!

The current error is because both `nbsphinx` and `myst_nb` register the `.ipynb` suffix, which in the vast majority of cases totally makes sense.

Here it's causing problems, even though, ironically, no `.ipynb` files are used at all.

**Comment by astrojuanlu** [comment]
I see! Would it make sense to (for the sake of the experiment) replace nbsphinx with myst-nb? However I understand that the example gallery will fail... so I don't know if we will get very far.

**Comment by mgeier** [comment]
> Would it make sense to (for the sake of the experiment) replace nbsphinx with myst-nb?

Yes, that's what I'm trying to do here. I didn't expect there to be that many stumbling blocks.

I'm trying at https://github.com/spatialaudio/nbsphinx/pull/578 to accept an override for `.ipynb`.

> However I understand that the example gallery will fail...

I expect the thumbnails to fail, but maybe the gallery itself will work?

**Comment by astrojuanlu** [comment]
It's working now! Build should be up soon

**Comment by astrojuanlu** [comment]
https://poliastro--1261.org.readthedocs.build/en/1261/

**Comment by astrojuanlu** [comment]
So, if I understand correctly, now we are using MyST-NB to parse the notebooks instead of jupytext through nbsphinx?

**Comment by mgeier** [comment]
Cool!

As expected, the thumbnails are missing (except the once specified in `conf.py`): https://poliastro--1261.org.readthedocs.build/en/1261/gallery.html

**Comment by mgeier** [comment]
> So, if I understand correctly, now we are using MyST-NB to parse the notebooks instead of jupytext through nbsphinx?

Yes. At least that's how I understand it.

**Comment by mgeier** [comment]
MyST doesn't seem to support `<div class="alert alert-info">` boxes, see the bottom of https://poliastro--1261.org.readthedocs.build/en/1261/examples/Analyzing%20NEOs.html.
AFAIK, they have a different markup for admonitions (which doesn't work in JupyterLab, though).

**Comment by astrojuanlu** [comment]
I think this experiment is complete @mgeier ? I summarized my findings here https://docs.readthedocs.io/en/stable/guides/jupyter.html (and we are sticking with nbsphinx in poliastro)

**Comment by mgeier** [comment]
Yes, as far as I'm concerned, this experiment is complete. It led to an improvement in `nbsphinx` (https://github.com/spatialaudio/nbsphinx/pull/578), which is great.

Thanks for writing the guide, I think this is really helpful!

**Pull request closed without merging**
