### PR TITLE
New GroundtrackPlotter feature

### PR DESCRIPTION
**Pull request by jorgepiloto**
##### About

This feature was suggested in #497, almost two years ago. Now that `poliastro` has a `poliastro.earth` subpackage and that `plotly` library offers great maps utilities it was finally possible to implement this plotter relatively easy and without the addition of any new dependencies.

Several advantages of this plotly based plotter are:

- It is highly customizable
- Supports both 2D and 3D representations
- Interactive figures
- Works with past and future epochs

##### Example case
```python
from poliastro.examples import iss, molniya
from poliastro.earth.plotting.groundtrack import GroundtrackPlotter
from poliastro.earth import EarthSatellite
from poliastro.util import time_range
from astropy import units as u


# Initialize both satellite orbits without spacecraft data
earth_iss = EarthSatellite(iss, spacecraft=None)
earth_molniya = EarthSatellite(molniya, spacecraft=None)

# Generate time spans
iss_times = time_range(start=earth_iss.orbit.epoch, periods=100, end=earth_iss.orbit.epoch + 12 * u.h)
molniya_times = time_range(start=earth_molniya.orbit.epoch, periods=100, end=earth_molniya.orbit.epoch + 48 * u.h)

# Plot both orbits
gt = GroundtrackPlotter()
gt.plot(earth_iss, iss_times, label="ISS", color="blue")
gt.plot(earth_molniya, molniya_times, label="Molniya", color="red")
```
Which outputs:
newplot

You can simply move to a three-dimensional representation by running:

```python
gt.update_geos(projection_type="orthographic")
```

This is the final result:

newplot (3)

### CODE REVIEW

**Comment by jorgepiloto** [comment]
Sorry for this late answer, I am busy these days but glad you liked this new feature. Let me fix those quality checks and if you want, I can also push within this pull a new documentation example :+1:

**Comment by astrojuanlu** [comment]
Excellent!

**Comment by jorgepiloto** [comment]
After squashing commits, I am ready for a review on this new feature. Some logic behind the plotter was changed in order to improve customization. For example, it is possible to customize the markers and also add any kind of location within the map by accessing the `add_trace` method. Any comments on this will be useful for me to reformat implementation if required :rocket:

**Review by astrojuanlu — APPROVED** [review]
Let's get this in :heart_eyes:

**Comment by astrojuanlu** [comment]
I think the API is excellent, and the implementation very tidy and clean. Also, having the notebook is just awesome! Will merge when all tests pass.

**Comment by jorgepiloto** [comment]
Thanks for the feedback @astrojuanlu ! Let me merge this and close original issue. I wish if there is any tool out there to properly test plotly based figures, so coverage does not decrease when implementing these kind of visualization features...

**Pull request merged**
