### PR TITLE
Update validation trigger to main branch

### PR DESCRIPTION
**Pull request by jorgepiloto**
Solves for #1119, in particular for the validation trigger.

### CODE REVIEW

**Comment by jorgepiloto** [comment]
Yet another classic failure on the validation trigger... I wonder why this requests admin privileges if it was able to work properly without those. May the tokens need to be updated? 🤔

**Comment by DhruvSondhi** [comment]
Where can you see the failure? 🤔

**Comment by jorgepiloto** [comment]
> Where can you see the failure? thinking
@DhruvSondhi 

If you click on "Show environments", you will see that the request was rejected because no admin rights.

**Review by astrojuanlu — APPROVED** [review]
Thanks @jorgepiloto ! 🤖

**Pull request merged**
