### PR TITLE
WIP: Adapting to Alabaster!

### PR DESCRIPTION
**Pull request by shreyasbapat**
Issues: 
Identified! -> The min-width in basic.css for the body is set as 450px. That can be fixed. I am unable to use custom css for some reasons. I will investigate. } Probably we can achieve the width issue in a different PR.

Circle CI Badge -> There is no Circle CI badge in default badges. Probably we wll have to create one :/ 

Every other thing seems fine!
Live link: http://poliastro-docs.shreyasb.com/en/theme-change_docs/

Solves : #337 #420 #418 #281

### CODE REVIEW

**Comment by shreyasbapat** [comment]
screenshot from 2018-07-29 07-24-23
Look at the bottom right corner!

**Comment by shreyasbapat** [comment]
I don't know why the build fails on CIrcle CI.
Here is the build on RTD. https://shreyas-poliastro.readthedocs.io/en/change_theme/

**Comment by Juanlu001** [comment]
Can't you access the CircleCI build? This is the error:

```
sphinx.errors.SphinxWarning: favicon file 'favicon.ico' does not exist
```

So I guess we need a favicon? :wink:

**Comment by shreyasbapat** [comment]
That's already there :/

**Comment by shreyasbapat** [comment]
https://github.com/poliastro/poliastro/blob/eeb14e20db5536ab40b543437a9dbbb9e573f19a/docs/source/_static/favicon.ico

**Comment by Juanlu001** [comment]
So maybe it's looking for it in the wrong path, no?

**Comment by shreyasbapat** [comment]
I have already set `html_static_path`. And obviously I am building the same thing on RTD. See this, it has a favicon: https://shreyas-poliastro.readthedocs.io/en/change_theme/

**Comment by Juanlu001** [comment]
From the build logs:

```
WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist
WARNING: favicon file 'favicon.ico' does not exist
```

source: https://readthedocs.org/projects/shreyas-poliastro/builds/7567619/

**Comment by Juanlu001** [comment]
Also, notice that the Read the Docs menu is broken, at least in Firefox:

screenshot_2018-08-01 poliastro - astrodynamics in python poliastro 0 11 dev0 documentation

**Comment by shreyasbapat** [comment]
I am so sorry! I was busy for some days. I will look into this!

**Comment by shreyasbapat** [comment]
Closing this. I will open another PR in some minutes!

**Pull request closed without merging**
