### PR TITLE
Update constants dj

### PR DESCRIPTION
**Pull request by DhruvJ22**
Update read docs to incorporate new general.py -> GM_moon and mean_elements.py

----
:books: Documentation preview :books:: https://poliastro--1569.org.readthedocs.build/en/1569/

### CODE REVIEW

**Comment by astrojuanlu** [comment]
I don't see any changes in the documentation: https://poliastro--1569.org.readthedocs.build/en/1569/autoapi/poliastro/constants/general/index.html#module-contents

An idea on how to do it: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autoattribute

(Came from https://stackoverflow.com/a/40488936/554319)

Also, this pull request needs

1. a rebase on top of `main` - for this, you'll have to update your `main` branch with respect to `poliastro/poliastro`, and then rebase your `update_constants_dj` branch.
2. uncommit the modified images.

**Review by astrojuanlu — CHANGES_REQUESTED** [review]
I don't see any changes in the documentation: https://poliastro--1569.org.readthedocs.build/en/1569/autoapi/poliastro/constants/general/index.html#module-contents

An idea on how to do it: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autoattribute

(Came from https://stackoverflow.com/a/40488936/554319)

Also, this pull request needs

1. a rebase on top of `main` - for this, you'll have to update your `main` branch with respect to `poliastro/poliastro`, and then rebase your `update_constants_dj` branch.
2. uncommit the modified images.

**Comment by DhruvJ22** [comment]
@astrojuanlu I have added a few comments with "#:" for docs.

**Comment by astrojuanlu** [comment]
Well, looking at https://poliastro--1569.org.readthedocs.build/en/1569/autoapi/poliastro/constants/general/index.html, I don't see any difference. But the syntax looks correct. Summoning my docs expert @humitos, do you have any idea what might be happening here? (Trying to add docstrings to module properties using the `#: ` syntax)

**Comment by humitos** [comment]
@astrojuanlu @DhruvJ22 I think documenting constants with `#:` is not supported on Sphinx AutoAPI: https://github.com/readthedocs/sphinx-autoapi/issues/344#issue-1322107196 😞

**Comment by astrojuanlu** [comment]
Thanks @humitos, that's too bad. @DhruvJ22 we should abandon this effort for now; thanks for trying it though! Closing

**Pull request closed without merging**
