### PR TITLE
VHP porkchops and Jupyter Notebook example

### PR DESCRIPTION
**Pull request by jorgepiloto**
I added the VHP option for porkchops, which is related to the arrival velocity at target body. Also, I thought it would be interesting to have a Jupyter Notebook example on this new functionality before starting with #559.

### CODE REVIEW

**Comment by Juanlu001** [comment]
Looking forward to rebase this one :)

**Comment by jorgepiloto** [comment]
There we go! I still need to study in depth more plotting options related to `porkchops`. Also the idea for plotting this figures between other bodies such us asteroids may be interesting :rocket:

**Comment by jorgepiloto** [comment]
There we go! I still need to study in depth more plotting options related to `porkchops`. Also the idea for plotting this figures between other bodies such us asteroids may be interesting :rocket:

**Comment by Juanlu001** [comment]
Thanks @jorgepiloto !

**Pull request merged**
