### PR TITLE
Disabled parallel jit for 32bit

### PR DESCRIPTION
**Pull request by airpods69**
For issue #1399

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Thanks for your contribution @airpods69!

Can someone with a 32-bit system try this out? @byang12159, @olebole?

(That will buy us time while we figure out what to do with Azure Pipelines https://github.com/poliastro/poliastro/issues/1456

**Comment by astrojuanlu** [comment]
The doc failures in principle are unrelated. Restarting again.

**Comment by astrojuanlu** [comment]
Well, I made a bit of a mess to this branch but the pipelines should be passing now. There is a problem with RTD that we can figure out later. My request for someone with a 32bit system to give this a try stands.

**Comment by airpods69** [comment]
I could try making a vm with a 32 bit OS to check if it works

Sounds good? Or do we need bare metal stuff

**Comment by astrojuanlu** [comment]
Go ahead @airpods69 !

**Comment by olebole** [comment]
I just checked this on a i386 chroot and it works. When reverting the jit decorator patch
```diff
--- a/src/poliastro/core/elements.py
+++ b/src/poliastro/core/elements.py
@@ -146,7 +148,7 @@ def coe2rv(k, p, ecc, inc, raan, argp, nu):
     return ijk
 
 
-@jit(parallel=True)
+@jit(parallel=sys.maxsize > 2 ** 31)
 def coe2rv_many(k, p, ecc, inc, raan, argp, nu):
 
     n = nu.shape[0]
```
I could also reproduce the bug.

**Comment by astrojuanlu** [comment]
Thanks a lot @olebole ! This is good to go then 🚀

**Comment by astrojuanlu** [comment]
Congrats @airpods69 on your first pull request! 🎉

**Comment by airpods69** [comment]
thanks!!

**Pull request merged**
