### PR TITLE
Description for modules & sub-modules in Core package

### PR DESCRIPTION
**Pull request by DhruvSondhi**
Hello, 
This PR aims to implement #1055.
Cheers 😄

### CODE REVIEW

**Review by astrojuanlu — CHANGES_REQUESTED** [review]
I don't think this has a place in poliastro, sorry. We either add a description of the package or we leave it blank, but explaining basic Python concepts should not be done here.

**Comment by DhruvSondhi** [comment]
No worries ... We can go with the description of the subpackage instead if that's more acceptable or else leave it out 🤔

**Review by astrojuanlu — CHANGES_REQUESTED** [review]
I don't think stating the directory structure is very useful. At the same time, I am unable to find good examples of module docstrings that I like. I'm sorry for not being able to provide useful guidance here, but honestly I am not sure what I expect to see here, until someone proposes something and I say "oh, that looks nice!"

**Comment by astrojuanlu** [comment]
> I marked this pull request as draft, because there are no changes since the last review, and I also unsubscribed. Please ask me for a review when it's ready. And if you are still waiting for my guidance on what to write, I have no other option but to ask you to wait a bit more, sorry.

**Pull request closed without merging**
