### PR TITLE
New plotting maneuver feature

### PR DESCRIPTION
**Pull request by jorgepiloto**
This pull request solves for #1349 by adding a new method to the `BaseOrbitPlotter` and redefining it for the `StaticOrbitPlotter` (following the same approach used by other similar methods). It was also added to the `_PlotlyOrbitPlotter` so the feature is accessible no matter the plotter being used.

Before merging this, the following tasks list needs to be completed:

- [ ] Add the corresponding tests to cover the logic behind this new feature.
- [ ] Simplify examples using the `plot_trajectory` to draw maneuver paths.

### CODE REVIEW

**Comment by jorgepiloto** [comment]
Progress on this:

Solarized dark             |  Solarized Ocean
:-------------------------:|:-------------------------:
  |  

I am happy with the result from the static plotters although not so satisfied with the markers from the interactive plotters. What do you think about those,  @astrojuanlu?

**Comment by jorgepiloto** [comment]
And here it is result for the interactive 2D plotters:

<div align="center">

</div>

**Comment by astrojuanlu** [comment]
I think this looks great! After addressing `E741 ambiguous variable name 'l'` this is ready for review I think

**Review by astrojuanlu — APPROVED** [review]
Looks good to me!

**Comment by jorgepiloto** [comment]
Oh! I was going to update some of the notebooks with this new feature but saw you just merged it @astrojuanlu. Let me open another PR then 🚀

**Comment by astrojuanlu** [comment]
Woops, sorry! Sure, go ahead 💪🏽

**Pull request merged**
