### PR TITLE
Small change to allow rv_pqw to be called with 1-D arrays.

### PR DESCRIPTION
**Pull request by Josvth**
Allows for calculation with multiple p's, ecc's and nu's.

### CODE REVIEW

**Comment by Juanlu001** [comment]
Hi @Josvth, thanks for contributing to poliastro! :tada:

The "ci/circleci: quality" step is complaining because the code does not follow Black, our style guide. Just for learning purposes, you can fix it yourself by doing:

```
pip install tox
tox -e reformat
```

and then make sure that you did it correctly by doing:

```
tox -e check
```

After that, the quality test will pass and all the tests will run.

Also, for a :top: pull request, you can try adding a new test with the functionality that _now works thanks for your change_. Let us know if you want us to guide you, and feel free to [join our chat](https://riot.im/app/#/room/#poliastro:matrix.org).

**Comment by Josvth** [comment]
@Juanlu001 thanks for the feedback! The tox command worked perfectly. But how do I now change the pull request? Or should I make a new one instead?

I won't have time to write an unit test tonight. But where and how would I do so?

**Comment by Juanlu001** [comment]
If you commit and push the pull request will get updated automatically, and it will hold all the commits you make to `master` until we decide to merge it.

> I won't have time to write an unit test tonight.

We are not in a hurry :)

> But where and how would I do so?

To make things easier, you can add it to the `Examples` section of the documentation, right bel

**Comment by Juanlu001** [comment]
Hi @Josvth! Do you still want to take care of this? Please reach out if you have any questions!

**Comment by Josvth** [comment]
> Hi @Josvth! Do you still want to take care of this? Please reach out if you have any questions!

I will get back to this after the IAC. Did you receive the email I send you?

**Comment by Juanlu001** [comment]
> I will get back to this after the IAC. Did you receive the email I send you?

No I didn't, please resend :blush:

**Comment by Josvth** [comment]
> > I will get back to this after the IAC. Did you receive the email I send you?
> 
> No I didn't, please resend 😊

Resend on the gmail in your Readme.md. Is that mail still active?

**Comment by Juanlu001** [comment]
Got it, answer soon :)

**Comment by Josvth** [comment]
@astrojuanlu I want to pick this up again but its been a while. Where to start?

**Comment by astrojuanlu** [comment]
Hi @Josvth, glad to hear back from you! :blush: 

My recommendation is that you rebase this pull request, because we have changed all the Continuous Integration infrastructure. To do that, you roughly have to:

* Make sure you have two entries in `git remote show`: one for your fork, and one for the central repository
* `git fetch <name_of_central_remote>` to make git aware of our latest changes
* `git rebase <name_of_central_remote>/master` - I don't expect any conflicts here
* `git push --force` to overwrite the history of this pull request

If you have any questions don't hesitate to [join our chat](https://riot.im/app/#/room/#poliastro-czml:matrix.org)!

**Comment by astrojuanlu** [comment]
The images failure is not related to this pull request.

**Comment by astrojuanlu** [comment]
Too bad we didn't add a test, because I was trying to make use of this functionality and I can't seem to make it work.

This works:

```
In [27]: k, p, ecc, nu
Out[27]: (398600.44180000003, 11067.79, 0.83285, 1.611549764828964)

In [28]: rv_pqw(k, p, ecc, nu)
Out[28]:
(array([ -466.76393378, 11447.02190813,     0.        ]),
 array([-5.99622175,  4.75360122,  0.        ]))
```

But this doesn't:

```
In [29]: rv_pqw(np.full(4, k), np.full(4, p), np.full(4, ecc), np.full(4, nu))
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-29-59e780ea72e3> in <module>
----> 1 rv_pqw(np.full(4, k), np.full(4, p), np.full(4, ecc), np.full(4, nu))

~/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    399                 e.patch_message(msg)
    400
--> 401             error_rewrite(e, 'typing')
    402         except errors.UnsupportedError as e:
    403             # Something unsupported is present in the user code, add help info

~/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345
    346         argtypes = []

~/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/numba/six.py in reraise(tp, value, tb)
    666             value = tp()
    667         if value.__traceback__ is not tb:
--> 668             raise value.with_traceback(tb)
    669         raise value
    670

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function array>) with argument(s) of type(s): (list(array(float64, 1d, C)))
 * parameterized
In definition 0:
    TypingError: array(float64, 1d, C) not allowed in a homogeneous sequence
    raised from /home/juanlu/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/numba/typing/npydecl.py:472
In definition 1:
    TypingError: array(float64, 1d, C) not allowed in a homogeneous sequence
    raised from /home/juanlu/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/numba/typing/npydecl.py:472
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function array>)
[2] During: typing of call at /home/juanlu/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/poliastro/core/elements.py (75)


File "../../../.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/poliastro/core/elements.py", line 75:
def rv_pqw(k, p, ecc, nu):
    <source elided>
    """
    r_pqw = (np.array([cos(nu), sin(nu), 0 * nu]) * p / (1 + ecc * cos(nu))).T
    ^

```

And neither does this:

```
In [30]: rv_pqw(k, p, ecc, np.full(4, nu))
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-30-342bb1e05144> in <module>
----> 1 rv_pqw(k, p, ecc, np.full(4, nu))

~/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    399                 e.patch_message(msg)
    400
--> 401             error_rewrite(e, 'typing')
    402         except errors.UnsupportedError as e:
    403             # Something unsupported is present in the user code, add help info

~/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345
    346         argtypes = []

~/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/numba/six.py in reraise(tp, value, tb)
    666             value = tp()
    667         if value.__traceback__ is not tb:
--> 668             raise value.with_traceback(tb)
    669         raise value
    670

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function array>) with argument(s) of type(s): (list(array(float64, 1d, C)))
 * parameterized
In definition 0:
    TypingError: array(float64, 1d, C) not allowed in a homogeneous sequence
    raised from /home/juanlu/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/numba/typing/npydecl.py:472
In definition 1:
    TypingError: array(float64, 1d, C) not allowed in a homogeneous sequence
    raised from /home/juanlu/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/numba/typing/npydecl.py:472
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function array>)
[2] During: typing of call at /home/juanlu/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/poliastro/core/elements.py (75)


File "../../../.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/poliastro/core/elements.py", line 75:
def rv_pqw(k, p, ecc, nu):
    <source elided>
    """
    r_pqw = (np.array([cos(nu), sin(nu), 0 * nu]) * p / (1 + ecc * cos(nu))).T
    ^

[1] During: resolving callee type: type(CPUDispatcher(<function rv_pqw at 0x7fb5fa58a280>))
[2] During: typing of call at /home/juanlu/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/poliastro/core/elements.py (143)

[3] During: resolving callee type: type(CPUDispatcher(<function rv_pqw at 0x7fb5fa58a280>))
[4] During: typing of call at /home/juanlu/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/poliastro/core/elements.py (143)
```

Any idea @Josvth?

**Comment by astrojuanlu** [comment]
While trying to make this work I made this patch that simplifies the code a bit but doesn't make my use case work:

```diff
diff --git a/src/poliastro/core/elements.py b/src/poliastro/core/elements.py
index 17ebf02..4fe9904 100644
--- a/src/poliastro/core/elements.py
+++ b/src/poliastro/core/elements.py
@@ -72,9 +72,10 @@ def rv_pqw(k, p, ecc, nu):
     These formulas can be checked at Curtis 3rd. Edition, page 110. Also the
     example proposed is 2.11 of Curtis 3rd Edition book.
     """
-    r_pqw = (np.array([cos(nu), sin(nu), 0 * nu]) * p / (1 + ecc * cos(nu))).T
-    v_pqw = (np.array([-sin(nu), (ecc + cos(nu)), 0 * nu]) * sqrt(k / p)).T
-    return r_pqw, v_pqw
+    pqw = np.array([[cos(nu), sin(nu), 0], [-sin(nu), ecc + cos(nu), 0]]) * np.array(
+        [[p / (1 + ecc * cos(nu))], [sqrt(k / p)]]
+    )
+    return pqw
 
 
 @jit
@@ -140,13 +141,12 @@ def coe2rv(k, p, ecc, inc, raan, argp, nu):
     v_ijk: np.array
         Velocity vector in basis ijk
     """
-    r_pqw, v_pqw = rv_pqw(k, p, ecc, nu)
+    pqw = rv_pqw(k, p, ecc, nu)
     rm = coe_rotation_matrix(inc, raan, argp)
 
-    r_ijk = rm @ r_pqw
-    v_ijk = rm @ v_pqw
+    ijk = pqw @ rm
 
-    return r_ijk, v_ijk
+    return ijk
 
 
 @jit
```

**Comment by Josvth** [comment]
Those two exact functions 'rv_pqw' and 'coe2rv' I have been battling with in my version of the simulator as its core is doing multiple orbits (classical elements) at once. Interesting you quickly come to the same issue.

IIRC its a matter of doing the right multiplication arithmetic to make both of them work for 1d vectors. I know my solution for rv_pqw was elegant so I made that into a PR as it wouldn't hurt your code.

The coe2rv I at one point had modified with ugly np.einsum operations.

I am actually not sure if I still use either of those I think for rv_pqw I do. Let me dig around in my code to see how I solved it in the end. Maybe it saves you some time.

**Comment by astrojuanlu** [comment]
Some of the approaches might be solved by this workaround:

https://github.com/numba/numba/issues/4470#issuecomment-523395410

**Comment by astrojuanlu** [comment]
Scratch that. It allows the user to do `np.array(np.array([...]))`, but not `np.array([np.array([...]), np.array([...])])`.

**Comment by Josvth** [comment]
A better JIT compatible implementation of rv_pqw in #1046

**Pull request merged**
