### PR TITLE
Backports for 0.16.3

### LINKED ISSUE #1493: poliastro.twobody.Orbit import error
Importing Orbit from poliastro.twobody results in an attribute error.

🐞 **Problem**

On macOS 12.3, I performed an install using pip and the instructions for downloading the latest build from GitHub and am getting an attribute error when importing  `Orbit` as follows:

```
from poliastro.twobody import Orbit
```

Here is the resulting Attribute error that got output:
```
AttributeError                            Traceback (most recent call last)
/Users/reecehumphreys/Developer/Personal/ODAP/notebooks/Introduction.ipynb Cell 27' in <cell line: [1]()>()
----> 1[ from poliastro.twobody import Orbit

File ~/.virtualenvs/odap/lib/python3.9/site-packages/poliastro/twobody/__init__.py:1, in <module>
----> ]()[1]()[ from poliastro.twobody.orbit import Orbit
      ]()[3]()[ __all__ = ["Orbit"]

File ~/.virtualenvs/odap/lib/python3.9/site-packages/poliastro/twobody/orbit/__init__.py:1, in <module>
----> ]()[1]()[ from poliastro.twobody.orbit.scalar import Orbit
      ]()[3]()[ __all__ = ["Orbit"]

File ~/.virtualenvs/odap/lib/python3.9/site-packages/poliastro/twobody/orbit/scalar.py:6, in <module>
      ]()[4]()[ import numpy as np
      ]()[5]()[ from astropy import time, units as u
----> ]()[6]()[ from astropy.coordinates import (
      ]()[7]()[     ICRS,
      ]()[8]()[     CartesianDifferential,
      ]()[9]()[     CartesianRepresentation,
     ]()[10]()[     get_body_barycentric,
     ]()[11]()[ )
     ]()[13]()[ from poliastro.frames.util import get_frame
     ]()[14]()[ from poliastro.threebody.soi import laplace_radius

File ~/.virtualenvs/odap/lib/python3.9/site-packages/astropy/coordinates/__init__.py:16, in <module>
     ]()[14]()[ from .earth import *
     ]()[15]()[ from .transformations import *
---> ]()[16]()[ from .builtin_frames import *
     ]()[17]()[ from .name_resolve import *
     ]()[18]()[ from .matching import *

File ~/.virtualenvs/odap/lib/python3.9/site-packages/astropy/coordinates/builtin_frames/__init__.py:32, in <module>
     ]()[30]()[ from .fk4 import FK4, FK4NoETerms
     ]()[31]()[ from .galactic import Galactic
---> ]()[32]()[ from .galactocentric import Galactocentric, galactocentric_frame_defaults
     ]()[33]()[ from .supergalactic import Supergalactic
     ]()[34]()[ from .altaz import AltAz

File ~/.virtualenvs/odap/lib/python3.9/site-packages/astropy/coordinates/builtin_frames/galactocentric.py:591, in <module>
    ]()[587]()[     return get_matrix_vectors(galactocentric_coord, inverse=True)
    ]()[590]()[ # Create loopback transformation
--> ]()[591]()[ frame_transform_graph._add_merged_transform(Galactocentric, ICRS, Galactocentric)

AttributeError: 'TransformGraph' object has no attribute '_add_merged_transform']()
```

This seems to be an issue with AstroPy looking at the stack trace but I figured that I would bring it to your attention!

### LINKED ISSUE #1496: The `astropy<5,>=3.2` dependency makes poliastro not installable on Python 3.10.2 since astropy-4.3.1 does not install on that version of python
🐞 **Problem**

When installing poliastro trough pip on python 3.10.2 it uses `astropy-4.3.1` which fails installation with the error message `ImportError: cannot import name 'soft_unicode' from 'markupsafe'`. 

🖥 **Please paste the output of following commands**

<details>
  
```bash
# Paste your output here:
(poliastro) danielk@IRF033-danielk ~/python_scripts> pip freeze
appdirs==1.4.4
application-utility==1.3.2
arandr==0.1.10
btrfsutil==5.16.2
CacheControl==0.12.6
ceph==1.0.0
ceph-volume==1.0.0
cephfs==2.0.0
cephfs-shell==0.0.1
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
colorama==0.4.4
contextlib2==0.6.0.post1
crit==0.0.1
cryptography==36.0.1
Cython==0.29.28
distlib==0.3.4
distro==1.7.0
dnspython==2.2.0
docopt==0.6.2
gufw==21.4.0
html5lib==1.1
idna==3.3
importlib-metadata==4.8.1
keyutils==0.6
lensfun==0.3.3
lightdm-gtk-greeter-settings==1.2.2
lit==13.0.1.dev0
louis==3.21.0
manjaro-sdk==0.1
Markdown==3.3.6
menulibre==2.2.3
more-itertools==8.10.0
msgpack==1.0.3
mugshot==0.4.3
nftables==0.1
npyscreen==4.10.5
numpy==1.22.3
ordered-set==4.0.2
packaging==20.9
pacman-mirrors==4.23.2
pep517==0.12.0
pexpect==4.8.0
ply==3.11
progress==1.6
protobuf==3.19.4
psutil==5.9.0
ptyprocess==0.7.0
pycairo==1.20.1
pycparser==2.21
PyGObject==3.42.0
pyOpenSSL==21.0.0
pyparsing==3.0.1
PyQt5==5.15.6
PyQt5-sip==12.9.1
PySide6==6.2.3
python-distutils-extra==2.39
pyxdg==0.27
PyYAML==6.0
rados==2.0.0
ranger-fm==1.9.3
rbd==2.0.0
requests==2.27.1
resolvelib==0.5.5
retrying==1.3.3
rgw==2.0.0
screenkey==1.5
shiboken6==6.2.3
six==1.16.0
systemd-python==234
TBB==0.2
team==1.0
toml==0.10.2
tomli==2.0.0
udiskie==2.4.2
ufw==0.36.1
urllib3==1.26.8
vimiv==0.8.0
webencodings==0.5.1
zipp==3.7.0
```
</details>

💡 **Possible solutions**

Upgrading the dependency to astropy>=5 and consequence revising the usage of astropy accordingly would probably make poliastro also support python >= 3.10.

### PR DESCRIPTION
**Pull request by astrojuanlu**
Essentially backporting https://github.com/poliastro/poliastro/pull/1498 first, applying code style, and lifted the Astropy version constraint, hence fix #1496 and fix #1493.

@yakkonaut @danielk333, @ReeceHumphreys @kerel-fs could you please give this branch a try and verify that it works? When you do, we'll release poliastro 0.16.3.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
ICRS tests failed with a problem similar to https://github.com/astropy/astropy/issues/13007 and others, but supposedly these have been solved in Astropy 5.0.4 already. Rebuilding.

**Comment by astrojuanlu** [comment]
Tests passing now, but docs are broken ("No module named 'autoapi'"). Something was lost in translation I think, fixing.

**Comment by astrojuanlu** [comment]
CI is green now, ready for tests 👍🏽

**Comment by danielk333** [comment]
Can confirm that [astrojuanlu:backports-0.16.3](https://github.com/astrojuanlu/poliastro/tree/backports-0.16.3) branch with `pip install .` works as intended with the test script that before failed! :+1:

**Comment by astrojuanlu** [comment]
Thanks a lot @danielk333! Proceeding with the release 🚄

**Pull request merged**
