### PR TITLE
Test dev version of sphinx-hoverxref (redux)

### PR DESCRIPTION
**Pull request by astrojuanlu**
Continuation of #1231 (I should have left that one open)

### CODE REVIEW

**Comment by astrojuanlu** [comment]
@humitos Unless I'm mistaken, it looks like no projects were enabled now? See https://poliastro--1234.org.readthedocs.build/en/1234/autoapi/poliastro/twobody/orbit/index.html#poliastro.twobody.orbit.Orbit.from_vectors

**Comment by humitos** [comment]
@astrojuanlu can you trigger a re-build of this PR so it picks the latest changes from the extension?

**Comment by astrojuanlu** [comment]
@humitos sure thing!

**Comment by astrojuanlu** [comment]
It works 😍

**Comment by humitos** [comment]
Ooooohhhh, yeah! I love it! Thanks for helping me with the debugging, test, and QA process 😄

**Comment by astrojuanlu** [comment]
Using the new version 💪🏽

**Pull request merged**
