### PR TITLE
build: Remove upper bound on requires-python

### PR DESCRIPTION
**Pull request by matthewfeickert**
Remove upper bound on `requires-python` as advocated for in Henry Schreiner's blog post "Should You Use Upper Bound Version Constraints?".
   - c.f. https://iscinumpy.dev/post/bound-version-constraints/#pinning-the-python-version-is-special

----
:books: Documentation preview :books:: https://poliastro--1588.org.readthedocs.build/en/1588/

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@astrojuanlu This is ready for review. Let me know if you have any questions. :+1:

**Comment by jorgepiloto** [comment]
Thanks for addressing this, @matthewfeickert.

I agree about removing the upper bound on `requires-python`. On top of that, it would be interesting to add a `py311` test environment in [.circleci/config](https://github.com/poliastro/poliastro/blob/main/.circleci/config.yml) to be sure that `poliastro` also works with Python 3.11.

**Review by jorgepiloto — APPROVED** [review]

**Comment by matthewfeickert** [comment]
> I agree about removing the upper bound on `requires-python`. On top of that, it would be interesting to add a `py311` test environment in [.circleci/config](https://github.com/poliastro/poliastro/blob/main/.circleci/config.yml) to be sure that `poliastro` also works with Python 3.11.

Python 3.11 is coming out soon (this Monday [2022-10-24](https://peps.python.org/pep-0664/#schedule))! @jorgepiloto we could either wait for the release and then tack on those here, or if you'd prefer more atomic PRs I can do a followup PR on Monday evening once the new `python:3.11` Docker images are out. Your call. :+1:

**Comment by jorgepiloto** [comment]
You are right, @matthewfeickert. I forgot py311 is released tomorrow. Let's merge this 👍🏽

**Review by jorgepiloto — APPROVED** [review]

**Pull request merged**
