### PR TITLE
Inherit SS bodies from Body

### PR DESCRIPTION
**Pull request by jorgepiloto**
Solves #759 :rocket:

### CODE REVIEW

**Comment by jorgepiloto** [comment]
Not sure why the `test_orbit_is_pickable` fails :confused:

**Comment by Juanlu001** [comment]
Something broke at the bodies level:

```
In [1]: import pickle                                                                                                                                         

In [2]: from poliastro.bodies import Sun                                                                                                                      

In [3]: t = pickle.dumps(Sun)                                                                                                                                 

In [4]: pickle.loads(t)                                                                                                                                       
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-2b29055027ec> in <module>
----> 1 pickle.loads(t)

~/.pyenv/versions/3.7.3/envs/poliastro37/lib/python3.7/site-packages/astropy/constants/constant.py in wrapper(self, *args, **kwargs)
     35             @functools.wraps(meth)
     36             def wrapper(self, *args, **kwargs):
---> 37                 name_lower = self.name.lower()
     38                 instances = self._registry[name_lower]
     39                 if not self._checked_units:

AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by Juanlu001** [comment]
Interestingly, it's something with the constants:

```
In [22]: b = Body(None, 1.0, "Body")                                                                                                                          

In [23]: t = pickle.dumps(b)                                                                                                                                  

In [24]: q = pickle.loads(t)                                                                                                                                  

In [25]: b                                                                                                                                                    
Out[25]: Body (None)

In [26]: q                                                                                                                                                    
Out[26]: Body (None)

In [27]: b = Body(None, Sun.k, "Body")                                                                                                                        

In [28]: t = pickle.dumps(b)                                                                                                                                  

In [29]: q = pickle.loads(t)                                                                                                                                  
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-f28dafaa6051> in <module>
----> 1 q = pickle.loads(t)

~/.pyenv/versions/3.7.3/envs/poliastro37/lib/python3.7/site-packages/astropy/constants/constant.py in wrapper(self, *args, **kwargs)
     35             @functools.wraps(meth)
     36             def wrapper(self, *args, **kwargs):
---> 37                 name_lower = self.name.lower()
     38                 instances = self._registry[name_lower]
     39                 if not self._checked_units:

AttributeError: 'NoneType' object has no attribute 'lower'
```

And, in fact:

https://github.com/astropy/astropy/issues/9139

**Comment by Juanlu001** [comment]
With your permission, this will be superseded by #763. Let's find a simpler workaround in the meanwhile if you need this for #747, or wait until we merge the big refactor.

**Comment by jorgepiloto** [comment]
I will wait to fully implement SSO orbits until #763 is ready to be merged since it is critical. For the moment I am reviewing all the new reformat and checking differents data and tests :wink:

**Pull request closed without merging**
