### PR TITLE
Implement improved algorithm for rv2coe. Addresses #566

### LINKED ISSUE #566: Improve stability of `coe2rv`<->`rv2coe`
🐞 **Problem**

Because I have been bitten by lacking stability of orbital elements to cartesian vectors conversion
functions in the past, I have started a (mad) little experiment over in Julia land, see [here](https://github.com/JuliaAstro/AstroBase.jl/blob/master/test/orbit_ranges.jl).

I basically construct the valid ranges for the orbital elements for all orbit types (elliptic, hyperbolic, circular, equatorial, circular-equatorial) excluding obvious singularities and check for a certain number of permutations whether the transformation is transitive, i.e. `rv2coe(coe2rv(...))`.

I repeated this test for three different implementations:

- `poliastro`: A Julia implementation of the algorithm currently implemented in poliastro.
- `Orekit`: A Julia implementatopn of the algorithm implemented in Orekit.
- `AstroBase.jl`: A happy mash-up of the two above, i.e. special case handling of poliastro with elliptic/hyperbolic equations adapted from Orekit.

Here are the results (`rejected` means that impossible orbits were discarded):

**Poliastro**

I have not analzyed the results in detail but the current implementation in poliastro struggles across the board (the Julia port might also be buggy, but all three variants pass basic smoke tests).
```
Elliptic Orbits
===============
Testing 262144 combinations with 5 processes.
Passed 163840 (62%), failed 98304 (38%), rejected 0 (0%).
In 27.197244709 seconds.

Hyperbolic Orbits
=================
Testing 262144 combinations with 5 processes.
Passed 73728 (28%), failed 73728 (28%), rejected 114688 (44%).
In 20.730527165 seconds.

Circular Orbits
===============
Testing 4096 combinations with 5 processes.
Passed 39 (1%), failed 4057 (99%), rejected 0 (0%).
In 1.168262474 seconds.

Equatorial Orbits
=================
Testing 4096 combinations with 5 processes.
Passed 2560 (62%), failed 1536 (38%), rejected 0 (0%).
In 0.480839932 seconds.

Circular-Equatorial Orbits
==========================
Testing 64 combinations with 5 processes.
Passed 8 (12%), failed 56 (88%), rejected 0 (0%).
In 0.627632413 seconds.
```

**Orekit**

Orekit gets a perfect score on elliptic/hyperbolical but does 🤷‍♂️ on special cases. This is probably because the user is supposed to use the right *special* orbit class for non-elliptic orbits (a silly concept in my book). 
```
Elliptic Orbits
===============
Testing 262144 combinations with 5 processes.
Passed 262144 (100%), failed 0 (0%), rejected 0 (0%).
In 25.938678205 seconds.

Hyperbolic Orbits
=================
Testing 262144 combinations with 5 processes.
Passed 147456 (56%), failed 0 (0%), rejected 114688 (44%).
In 20.718426606 seconds.

Circular Orbits
===============
Testing 4096 combinations with 5 processes.
Passed 0 (0%), failed 4096 (100%), rejected 0 (0%).
In 1.151732604 seconds.

Equatorial Orbits
=================
Testing 4096 combinations with 5 processes.
Passed 4096 (100%), failed 0 (0%), rejected 0 (0%).
In 0.45797599 seconds.

Circular-Equatorial Orbits
==========================
Testing 64 combinations with 5 processes.
Passed 2 (3%), failed 62 (97%), rejected 0 (0%).
In 0.645712886 seconds.
```

**AstroBase.jl**

And finally the mash-up which takes the best of both worlds and generates a perfect score: https://github.com/JuliaAstro/AstroBase.jl/blob/master/src/TwoBody.jl#L56
```
Elliptic Orbits
===============
Testing 262144 combinations with 5 processes.
Passed 262144 (100%), failed 0 (0%), rejected 0 (0%).
In 27.107912912 seconds.

Hyperbolic Orbits
=================
Testing 262144 combinations with 5 processes.
Passed 147456 (56%), failed 0 (0%), rejected 114688 (44%).
In 21.958699757 seconds.

Circular Orbits
===============
Testing 4096 combinations with 5 processes.
Passed 4096 (100%), failed 0 (0%), rejected 0 (0%).
In 1.278563358 seconds.

Equatorial Orbits
=================
Testing 4096 combinations with 5 processes.
Passed 4096 (100%), failed 0 (0%), rejected 0 (0%).
In 0.560119618 seconds.

Circular-Equatorial Orbits
==========================
Testing 64 combinations with 5 processes.
Passed 64 (100%), failed 0 (0%), rejected 0 (0%).
In 0.726457916 seconds.
```

🎯 **Goal**

- Improve stability of `coe2rv` and by extension `Orbit.from_classical`
- If the user provides a valid orbit the conversions should not fail

💡 **Possible solutions**

- Implement AstroBase.jl algorithm in poliastro

📋  **Steps to solve the problem**

- [ ] Check if test methodology is sound
  - [ ] i.e. are all ranges selected correctly?
- [x] Maybe run the test on a beefier machine with even more samples
- [ ] Implement best algorithm
- [ ] Implement stronger argument checks in e.g. `Orbit.from_classical`
- ...
- [ ] Profit!

### PR DESCRIPTION
**Pull request by helgee**
Fixes #566 

I have implemented my combined algorithm and added a few smoke tests for all orbit types.

### CODE REVIEW

**Comment by helgee** [comment]
Is there a convenient way to run the toolchain (black, isort, etc...), locally?

And I am giving up for today...
The bloody thing worked locally but now with Anaconda reinstalled it's broken 🙈

**Comment by Juanlu001** [comment]
> Is there a convenient way to run the toolchain (black, isort, etc...), locally?

No, and I admit there should be. For the moment, you can do `isort -rc src/ && black src/`.

Good luck with that Anaconda installation :sweat_smile:

**Comment by helgee** [comment]
Makefile? 🤪

**Comment by Juanlu001** [comment]
I was thinking about tox actually: https://github.com/poliastro/poliastro/issues/509 (inspired by https://blog.ionelmc.ro/2014/05/25/python-packaging/)

**Comment by Juanlu001** [comment]
When #576 is merged, you will be able to do `tox -e check` to check all the quality steps.

Also, do you need help for this or just run out of patience? It will need a rebase in any case.

**Comment by helgee** [comment]
I don't have the patience right now...

Will get back to it soon!

**Comment by Himanshu-Garg** [comment]
sir, i can help in rearramging it.
if it doesn't bother you...

thank you

**Comment by helgee** [comment]
Alright! CI is finally all green :sweat_smile:

**Comment by Juanlu001** [comment]
Thanks for coming back to this! :) Will review soon

**Comment by Juanlu001** [comment]
Awesome @helgee :tada:

**Comment by helgee** [comment]
> `-pi <= nu < pi` (did I understand correctly)

Yup

**Pull request merged**
