### PR TITLE
EXP: Why are you using astroquery conftest.py

### PR DESCRIPTION
**Pull request by pllim**
Just trying random things in response to Slack post from @Juanlu001 regarding failure of #758 .

Ref: https://docs.pytest.org/en/latest/pythonpath.html

### CODE REVIEW

**Comment by pllim** [comment]
Interesting... Adding 2 empty files caused this failure: https://circleci.com/gh/poliastro/poliastro/5015

**Comment by Juanlu001** [comment]
Perplexing. Thanks @pllim, will give it a look!

**Comment by pllim** [comment]
Unfortunately, I am not familiar enough with this package to proceed. So, feel free to close this or push to my branch here using your maintainer power.

**Comment by Juanlu001** [comment]
Well, not that strange. This means we have a couple of mypy errors in the tests, which were not being detected before because the tests directory was not a Python package. Should be unrelated to the astroquery thing, I guess (I will fix them anyway).

**Comment by Juanlu001** [comment]
@pllim fixed mypy errors, now the tests are running. Let's see what happens...

**Comment by Juanlu001** [comment]
Adding these two empty files no longer has any effect.

**Comment by Juanlu001** [comment]
As described in https://github.com/poliastro/poliastro/pull/758#issuecomment-522350802, the issue is probably in the collection strategy of pytest-doctestplus. Closing this PR.

**Pull request closed without merging**
