### PR TITLE
Fixed OrbitPlotter.set_frame redraw colors

### PR DESCRIPTION
**Pull request by shreyasbapat**
Addresses #316

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Oh! Sure! I was offline for some days. Will add the test today only! Sorry for the delay

**Comment by shreyasbapat** [comment]
image
Here is the Screenshot :)

**Comment by Juanlu001** [comment]
Thanks! Rebase and I will merge :grin:

**Comment by shreyasbapat** [comment]
Rebased :)

**Comment by Juanlu001** [comment]
Thanks a lot!

**Pull request merged**
