### PR TITLE
Drop DOP853, use it from SciPy

### PR DESCRIPTION
**Pull request by Juanlu001**

### CODE REVIEW

**Comment by Juanlu001** [comment]
The tests fail because the CI environment is not prepared to install SciPy from source. Still, I tested everything locally and can say that it works beautifully! Leaving this open until SciPy 1.4, I hope :)

**Comment by Juanlu001** [comment]
DOP853 is merged in SciPy and will make it to 1.4 🚀

**Comment by Juanlu001** [comment]
One test failed because of precision. We'll have to look at it more closely.

**Comment by Juanlu001** [comment]
This is very weird but... Running `pytest -k pressure` I can't reproduce the failure locally. There must be some side effect hiding somewhere.

**Comment by Juanlu001** [comment]
I am observing consistently different integration results locally and on CI... Still can't explain why.

Local:

```
527  ->	        assert_quantity_allclose(
528  	            [delta_ecc, delta_inc, delta_raan, delta_argp],
529  	            deltas_expected,
530  	            rtol=1e-1,
531  	            atol=1e-4,
532  	        )
(Pdb) p delta_ecc
-0.0013460077062927393
(Pdb) p delta_inc
0.0089233990832156
(Pdb) p delta_raan
-0.06806819263954367
(Pdb) p delta_argp
8.522910768155384
(Pdb) p deltas_expected
[-0.0013, 0.01, -0.07, 8.0]
(Pdb) p delta_eccs[-5:]
[0.0069337139834901446, 0.006933530860161914, 0.006931446985079755, 0.006930940640002971, 0.00692914659346084]
(Pdb) p rr.to(u.km).value[-5:]
array([[-5050.90214203, -4833.34947231,  6823.05662652],
       [-3053.99514278, -3436.53970397, -8997.83344003],
       [ 6998.16562039,  6935.86251469, -3345.34019433],
       [  838.3714786 ,  1231.88259464,  9838.12423887],
       [-6781.46103052, -6916.04604759, -1733.32464632]])
(Pdb) p Earth.k
<Quantity 3.98600442e+14 m3 / s2>
(Pdb) p initial.r
<Quantity [-5827.82064172, -6107.82975836, -5053.75306774] km>
(Pdb) p initial.v
<Quantity [ 2.46234586,  2.2755359 , -5.50086461] km / s>
(Pdb) p np.linspace(0, (tof).to(u.s).value, 4000) * u.s
<Quantity [0.00000000e+00, 1.29632408e+04, 2.59264816e+04, ...,
           5.18140735e+07, 5.18270368e+07, 5.18400000e+07] s>
(Pdb) p Earth.R.to(u.km).value
6378.1366
(Pdb) p Wdivc_sun.value
102037593062041.36
(Pdb) p rr.to(u.km).value[:5]
array([[-5827.82064172, -6107.82975836, -5053.75306774],
       [ 5365.76420123,  5166.38143991, -6790.29698791],
       [ 3760.40427419,  4157.96828232,  8686.21861923],
       [-6579.2023793 , -6517.45781877,  3749.50965264],
       [ -360.48451945,  -758.6716798 , -9844.06765151]])
(Pdb) p len(rr)
4000
(Pdb) p rr.to(u.km).value[1000:1005]
array([[ -5513.13479427,  -5825.07286262,  -5978.47017084],
       [  5531.46993768,   5321.83807371,  -6799.91199127],
       [  3494.45237671,   3890.10653817,   8639.02306703],
       [ -6756.42224621,  -6728.98675474,   2708.70873013],
       [    25.98092295,   -388.03075328, -10150.15083533]])

```

CI:

```
526  	        assert_quantity_allclose(
527  	            [delta_ecc, delta_inc, delta_raan, delta_argp],
528  	            deltas_expected,
529  	            rtol=1e-1,
530  ->	            atol=1e-4,
531  	        )
[EOF]
(Pdb) p delta_ecc
-0.001339378486575149
(Pdb) p delta_inc
0.008808501531606793
(Pdb) p delta_raan
-0.06815669319711333
(Pdb) p delta_argp
8.541329796090428
(Pdb) p deltas_expected
[-0.0013, 0.01, -0.07, 8.0]
(Pdb) p delta_eccs[-5:]
[0.0069293495658365595, 0.006929123244683012, 0.006927022560793396, 0.006926603395393624, 0.00692466775122022]
(Pdb) p rr.to(u.km).value[-5:]
array([[-4542.99975058, -4293.1759005 ,  7518.41767744],
       [-3654.76678721, -4022.94009678, -8480.12073252],
       [ 6773.98346998,  6674.48837593, -4237.57314684],
       [ 1535.89384525,  1929.72886442,  9671.0106016 ],
       [-6876.70591683, -6972.65426831,  -723.6852943 ]])
(Pdb) p Earth.k
<Quantity 3.98600442e+14 m3 / s2>
(Pdb) p initial.r
<Quantity [-5827.82064172, -6107.82975836, -5053.75306774] km>
(Pdb) p initial.v
<Quantity [ 2.46234586,  2.2755359 , -5.50086461] km / s>
(Pdb) p np.linspace(0, (tof).to(u.s).value, 4000) * u.s
<Quantity [0.00000000e+00, 1.29632408e+04, 2.59264816e+04, ...,
           5.18140735e+07, 5.18270368e+07, 5.18400000e+07] s>
(Pdb) p Earth.R.to(u.km).value
6378.1366
(Pdb) p Wdivc_sun.value
102037593062041.36
(Pdb) p rr.to(u.km).value[:5]
array([[-5827.82064172, -6107.82975836, -5053.75306774],
       [ 5365.76420123,  5166.38143991, -6790.29698791],
       [ 3760.40427419,  4157.96828232,  8686.21861923],
       [-6579.2023793 , -6517.45781877,  3749.50965264],
       [ -360.48451945,  -758.6716798 , -9844.06765151]])
(Pdb) p rr.to(u.km).value[1000:1005]
array([[ -5513.13514373,  -5825.07318886,  -5978.46950875],
       [  5531.46958208,   5321.83768954,  -6799.9125739 ],
       [  3494.45285628,   3890.10700724,   8639.02267495],
       [ -6756.42211072,  -6728.98658687,   2708.70947354],
       [    25.98039974,   -388.03128152, -10150.15080389]])

```

**Comment by Juanlu001** [comment]
By the way, building the interpolant takes a significant amount of time. It's true that the original code by Curtis uses an approximate function, but perhaps there's a faster way of running this test?

**Comment by Juanlu001** [comment]
What I have so far: the output of the integration is _exactly_ the same _up to a certain point_.

I did this both locally and in Circle CI:

```diff
diff --git a/src/poliastro/tests/tests_twobody/test_perturbations.py b/src/poliastro/tests/tests_twobody/test_perturbations.py
index 6bd14c0..63aaa01 100644
--- a/src/poliastro/tests/tests_twobody/test_perturbations.py
+++ b/src/poliastro/tests/tests_twobody/test_perturbations.py
@@ -484,6 +484,7 @@ def test_solar_pressure(t_days, deltas_expected):
         # in Curtis, the mean distance to Sun is used. In order to validate against it, we have to do the same thing
         sun_normalized = functools.partial(normalize_to_Curtis, sun_r=sun_r)
 
+        breakpoint()
         rr, vv = cowell(
             Earth.k,
             initial.r,
```

And then used a conditional breakpoint:

```
$ tox -r -e py37 -- -k pressure -vv -s  # To make sure it's recreated
...
> /home/juanlu/Development/poliastro/poliastro/src/poliastro/tests/tests_twobody/test_perturbations.py(488)test_solar_pressure()
-> rr, vv = cowell(
(Pdb) tbreak /home/juanlu/Development/poliastro/poliastro/src/poliastro/core/propagation.py:43, t0>5820361
Breakpoint 1 at /home/juanlu/Development/poliastro/poliastro/src/poliastro/core/propagation.py:43
(Pdb) c

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB continue >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Deleted breakpoint 1 at /home/juanlu/Development/poliastro/poliastro/src/poliastro/core/propagation.py:43
> /home/juanlu/Development/poliastro/poliastro/src/poliastro/core/propagation.py(43)func_twobody()
-> return du
(Pdb) p "{:.20f}".format(t0)
'5820410.37210091482847929001'
```

So far, same output. However, when I advance one second:

Locally:

```
(Pdb) tbreak /home/juanlu/Development/poliastro/poliastro/src/poliastro/core/propagation.py:43, t0>5820362
Breakpoint 3 at /home/juanlu/Development/poliastro/poliastro/src/poliastro/core/propagation.py:43
(Pdb) c
...
> /home/juanlu/Development/poliastro/poliastro/src/poliastro/core/propagation.py(43)func_twobody()
-> return du
(Pdb) p "{:.20f}".format(t0)
'5820444.70246601291000843048'
```

CI:

```
(Pdb) tbreak /root/repo/src/poliastro/core/propagation.py:43, t0>5820362
Breakpoint 4 at /root/repo/src/poliastro/core/propagation.py:43
(Pdb) c
...
> /root/repo/src/poliastro/core/propagation.py(43)func_twobody()
-> return du
(Pdb) p "{:.20f}".format(t0)
'5820444.70246601663529872894'
```

And, from there, the error builds up. In two cases the tests pass (because there is some tolerance), but in the intermediate case it doesn't.

To check:

* I am almost sure that I have installed the dependencies the same way and that I have the same version. Are there any other factors that might affect the result?
* Does this behavior happen with other integrators in the new IVP module?
* Does this behavior happen with the old `ode` interface? (Difficult to reproduce)
* Does this behavior stay if I put the upper time bound _before_ the "branching point"?

**Comment by Juanlu001** [comment]
Of course I could give up, increase the tolerance, change the test, look for a more robust way to test the same thing... But we want to _understand everything_ :sunglasses:

**Comment by Juanlu001** [comment]
@kerel-fs already confirmed the test failure, which means that there are two tasks:

* Understand why I can't reproduce it locally (if I'm the only one perhaps it's not that interesting... for the rest of the people)
* Fix the test

**Comment by noc0lour** [comment]
Test results on one of my machines:
```
src/poliastro/tests/tests_twobody/test_perturbations.py:530: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

actual = [-0.0013413188508273831, 0.00872526365723445, -0.06815196875822664, 8.544195407904073], desired = [-0.0013, 0.01, -0.07, 8.0], rtol = 0.1
atol = 0.0001, kwargs = {}, np = <module 'numpy' from '/home/andrej/virtualenvs/poliastro_dev/lib/python3.7/site-packages/numpy/__init__.py'>
_unquantify_allclose_arguments = <function _unquantify_allclose_arguments at 0x7f6e827f3620>

    def assert_quantity_allclose(actual, desired, rtol=1.e-7, atol=None,
                                 **kwargs):
        """
        Raise an assertion if two objects are not equal up to desired tolerance.
    
        This is a :class:`~astropy.units.Quantity`-aware version of
        :func:`numpy.testing.assert_allclose`.
        """
        import numpy as np
        from astropy.units.quantity import _unquantify_allclose_arguments
        np.testing.assert_allclose(*_unquantify_allclose_arguments(
>           actual, desired, rtol, atol), **kwargs)
E       AssertionError: 
E       Not equal to tolerance rtol=0.1, atol=0.0001
E       
E       Mismatch: 25%
E       Max absolute difference: 0.54419541
E       Max relative difference: 0.12747363
E        x: array([-1.341319e-03,  8.725264e-03, -6.815197e-02,  8.544195e+00])
E        y: array([-1.3e-03,  1.0e-02, -7.0e-02,  8.0e+00])
```

**Comment by Juanlu001** [comment]
I managed to reproduce the test failure locally using Docker, so it's definitely an installation problem.

**Comment by Juanlu001** [comment]
Trying to understand what's going on comparing Docker and local side to side. Something changes between `nfev = 132853` and `nfev = 132868`. 15 evaluations to go...

**Comment by Juanlu001** [comment]
|         | `(Pdb) p "{:.20f}".format((x ** 2 + y ** 2 + z ** 2))` | `(Pdb) p "{:.20f}".format((x ** 2 + y ** 2 + z ** 2) ** 1.5)` |
|---------|--------------------------------------------------------|---------------------------------------------------------------|
|  Docker | `'103251804.61914528906345367432'`                     | `'1049171479739.75854492187500000000'`                        |
| Local   | `'103251804.61914528906345367432'`                     | `'1049171479739.75842285156250000000'`                        |

And, to check it's not a dtypes problem:

|         | `"{:.20f}".format((7091.17117297555159893818 ** 2 + 7118.70008070942458289210 ** 2 + (-1513.67274389594149397453) ** 2) ** 1.5)` |
|---------|----------------------------------------------------------------------------------------------------------------------------------|
|  Docker |  `'1049171479739.75854492187500000000'`                                                                                          |
| Local   | `'1049171479739.75842285156250000000'`                                                                                           |

I can only say: **what the fuck**.

**Comment by Juanlu001** [comment]
So, basically:

```
$ docker run --rm -it python:3.7.5-stretch python -c 'print("{:.10f}".format((7091.17117297555159893818 ** 2 + 7118.70008070942458289210 ** 2 + (-1513.67274389594149397453) ** 2) ** 1.5))'
1049171479739.7584228516
$ docker run --rm -it python:3.7.5-buster python -c 'print("{:.10f}".format((7091.17117297555159893818 ** 2 + 7118.70008070942458289210 ** 2 + (-1513.67274389594149397453) ** 2) ** 1.5))'
1049171479739.7585449219
```

I guess there were changes in GCC 8.

**Comment by Juanlu001** [comment]
Conclusion:

> There might be small floating point differences, to the order of the machine precision, across different compilations of the same Python version

Perhaps a solution for this would be #707, but we won't tackle that in this pull request. We will rewrite the test instead.

**Comment by Juanlu001** [comment]
Well, after all this back and forth, I think I prefer to lower (even more) the tolerance of the test and eventually move this to https://github.com/poliastro/validation/.

**Comment by Juanlu001** [comment]
@nikita-astronaut The work has been completed :)

**Pull request merged**
