### PR TITLE
Was removed mention to `poliastro.testing` from issue template #Hackt…

### PR DESCRIPTION
**Pull request by hramirezq**
…oberfest

### CODE REVIEW

**Comment by jorgepiloto** [comment]
Hi @hramirezq, thanks for your pull request (solves #1012). Since `tests/` were removed from `src/poliastro/`, the `testing` module will not be found, so whole line must be removed.

**Review by astrojuanlu — CHANGES_REQUESTED** [review]
What @jorgepiloto said :)

We need to make a decision:

- Just remove the mention to `poliastro.testing`, because it's not there anymore, or
- Tell users to run the tests by checking out the repository

I think the latter is too much to ask for a humble bug report, so I say that we just remove it.

**Review by astrojuanlu — APPROVED** [review]
Looks good! Merging straight away

**Comment by astrojuanlu** [comment]
Thanks @hramirezq! :raised_hands:

**Comment by hramirezq** [comment]
Thanks for the advice, I hope to be more useful in the next days!

**Pull request merged**
