### PR TITLE
Switch to Jupytext

### PR DESCRIPTION
**Pull request by jorgepiloto**
Solves for #727 by switching `*.ipynb` files to `*.md` ones with the help of Jupytext.

### CODE REVIEW

**Comment by jorgepiloto** [comment]
Although tests are passing locally with `tox -e docs` and documentation is built up without problem it seems that Read The Docs complains about the build.

**Comment by astrojuanlu** [comment]
```
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/978/docs/source/examples/Analyzing the Parker Solar Probe flybys.md:"nbsphinx-thumbnail": No outputs in cell 57
```

:thinking: 

Can you try

```
export READTHEDOCS=1
tox -e docs
```

?

**Comment by jorgepiloto** [comment]
> ```
> export READTHEDOCS=1
> tox -e docs
> ```

Previous commands were not successful... :cry: 

I did not modify the `docs/source/jupyter.rst` file which contains a `toctree` referencing the name of each notebook but with `*.ipynb` extension. It is strange that Sphinx does not complain about the fact those files do not exist anymore. Let me check also for that :+1:

**Comment by jorgepiloto** [comment]
> export READTHEDOCS="True"
> tox -e docs

If changing to "True" I am finally able to recreate the errors from RTD. Therefore, should we force `nbsphinx_execute = True` no matter the environment?

**Comment by astrojuanlu** [comment]
@jorgepiloto is this still a draft? Or is it ready for review?

**Comment by jorgepiloto** [comment]
I still need to deal with Binder notebooks but not sure how to do that :thinking:

**Comment by astrojuanlu** [comment]
True, opening the `.md` example in Binder now displays a text file. Doing just `%pip install jupytext` didn't fix it. But perhaps adding it to `requirements.txt` [as done in this demo](https://github.com/mwouts/PythonDataScienceHandbook/commit/c476c13bb67e6a8d5a340f96dbf827b4cd675764) will do the trick?

**Comment by astrojuanlu** [comment]
(Notice that in this case you would need to add it to `requirements.in` and then `pip-compile` to generate `requirements.txt` - ping me if you need help)

**Comment by astrojuanlu** [comment]
Relevant: https://github.com/mwouts/jupytext/#jupytexts-contents-manager

**Comment by jorgepiloto** [comment]
> (Notice that in this case you would need to add it to `requirements.in` and then `pip-compile` to generate `requirements.txt` - ping me if you need help)

I ran `echo "jupytext" >> requirements.in && pip-compile` and although it was added to the `requirements.txt` a lot of other deps were upgraded, is this normal? I thought required packages were defined in the `pyproject.toml`...

**Comment by astrojuanlu** [comment]
Yes, the dependencies for users that do `pip install poliastro` are defined in `pyproject.toml`. But Binder does not know how to read that, so we need to repeat some of them in `requirements.in`. So, yeah, it's a duplication :/

**Comment by astrojuanlu** [comment]
YAYYYYYYY it worked! :heart_eyes:

**Comment by astrojuanlu** [comment]
Awesome work @jorgepiloto! :rocket:

**Pull request merged**
