### PR TITLE
Fix issue 526

### PR DESCRIPTION
**Pull request by aOrionis**
Addresses #526 

Have added the tests, but had to take the default value for the eccentricity as the place where I pulled the hill radius data from wasn't considering eccentricity of the orbit in their equations.

### CODE REVIEW

**Comment by aOrionis** [comment]
@Juanlu001 Please review

**Comment by Juanlu001** [comment]
Hi @aOrionis, thanks a lot for this pull request! However, we are in the process of reviewing https://github.com/poliastro/poliastro/pull/533, which started 4 days ago. In fact, the codebases are very similar, so if you don't mind let us close this one and continue there.

**Comment by aOrionis** [comment]
That’s fine. How will we continue there? I just close this PR and then?

**Comment by Juanlu001** [comment]
Let's close this PR and I encourage you to take any of the other "good first issue"s https://github.com/poliastro/poliastro/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22. Also, leave a mention there that you are working on it, so others can notice :) Thanks a lot!

**Pull request closed without merging**
