### PR TITLE
Added the plotly 3.0 Compatibility to OrbitPlotter2D

### PR DESCRIPTION
**Pull request by shreyasbapat**
Tested. It Works! We may need to bump the required plotly version in setup.py to get the CI build correctly.

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Addresses #397

**Comment by shreyasbapat** [comment]
screenshot from 2018-07-06 12-21-51
Is there something which I am missing? Coz you can see the plots in Jupyter Lab and I can't :/

**Comment by shreyasbapat** [comment]
Do I need to install the plotly extension like this: ``jupyter labextension install @jupyterlab/plotly-extension`` ? But this essentially requires user to install it too and it has prerequisites such as nodejs  and npm.

**Comment by shreyasbapat** [comment]
Installing the extension worked for me. But probably we should mention this somewhere in the docs. Or install these dependencies automatically while shipping poliastro?

**Comment by shreyasbapat** [comment]
I think there is a similar issue in documentation and there is some missing js extension which needs to be installed

**Comment by shreyasbapat** [comment]
The plots will now be visible in the docs!

**Comment by Juanlu001** [comment]
> But probably we should mention this somewhere in the docs.

Totally! At least, refer the people to the proper link. Related: #338 

>  But this essentially requires user to install it too and it has prerequisites such as nodejs and npm.

Yes... I currently use conda for that, so maybe I should update the conda packages, and for pip users we should add more info to the docs. https://github.com/conda-forge/poliastro-feedstock/issues/17

> Or install these dependencies automatically while shipping poliastro?

I don't know how to do that, for the moment let's focus on explaining the manual steps.

**Comment by shreyasbapat** [comment]
So, specifically where should I add the note?

**Comment by Juanlu001** [comment]
I see that we're having problems displaying the output:

https://shreyas-poliastro.readthedocs.io/en/rerun-notebooks/examples/Plotting%20in%203D.html

> Data type cannot be displayed: application/vnd.plotly.v1+json

I found a comment on an unrelated project that might be interesting:

https://github.com/fsprojects/IfSharp/issues/142#issuecomment-327116272

Could you please try again with Plotly 3.0 and the `init_notebook_mode` with `connected` both `True` and `False`? Bear in mind that you cannot refer to specific builds in Read the Docs, so take screenshots.

**Comment by shreyasbapat** [comment]
Okay! On it!

**Comment by shreyasbapat** [comment]
Meanwhile I found this! I don't know at what level it is relatable, but I also installed the same extension and problem occured.
https://www.npmjs.com/package/@jupyterlab/plotly-extension/v/0.16.0

**Comment by shreyasbapat** [comment]
init_notebook_mode(connected=True) does the job for us!

**Comment by Juanlu001** [comment]
Does `init_notebook_mode(connected=False)` work also?

**Comment by shreyasbapat** [comment]
Yes, that works too!

**Comment by shreyasbapat** [comment]
screencapture-shreyas-poliastro-readthedocs-io-en-rerun-notebooks-examples-plotting-in-3d-html-2018-07-07-01_59_59
This is not done :confused:

**Comment by shreyasbapat** [comment]
I mean it's so inconsistent. Sometimes they load, sometimes they don't. 
Refresh the same page multiple times and you will see the plots appearing and disappearing:
https://shreyas-poliastro.readthedocs.io/en/rerun-notebooks/examples/Plotting%20in%203D.html

**Comment by shreyasbapat** [comment]
One more thing. It's just my hypothesis. Works well on FIrefox, Not on chrome? Some browser extension is needed?

**Comment by Juanlu001** [comment]
> Works well on FIrefox, Not on chrome? Some browser extension is needed?

I can confirm... Perhaps there's something wrong with this approach? We'll have to investigate more.

**Comment by Juanlu001** [comment]
There's an intermittent error "Uncaught TypeError: Plotly.newPlot is not a function". I suspect it has to do with how the default Read the Docs HTML theme loads some asynchronous JavaScript stuff...

**Comment by Juanlu001** [comment]
Just to discard the low hanging fruit, could you try if `init_notebook_mode(connected=False)` produces fewer errors?

**Comment by Juanlu001** [comment]
Another idea: can you add another JS library to the first cell?

https://github.com/plotly/plotly.py/issues/1033#issuecomment-402894617

**Comment by shreyasbapat** [comment]
No changes in the state by changing Connected to False. 
I will try to add another script.

**Comment by shreyasbapat** [comment]
LOL! 
Adding that library removed every other plot that was being plotted a while ago! 
https://shreyas-poliastro.readthedocs.io/en/rerun-notebooks/examples/Plotting%20in%203D.html

**Comment by shreyasbapat** [comment]
Though now I can see this: ``ReferenceError: require is not defined[Learn More]``

**Comment by shreyasbapat** [comment]
I tried adding some other scripts as well. It doesn't work. I will investigate further.

**Comment by shreyasbapat** [comment]
BTW @Juanlu001  I saw somewhere that changing the theme would do the job. What exactly will the theme change?

**Comment by shreyasbapat** [comment]
Oh! We won't change the theme. Sorry

**Comment by Juanlu001** [comment]
Well, at least let's see if that fixes the issue, and then we can decide what to do.

**Comment by Juanlu001** [comment]
This needs a rebase on current master.

**Comment by Juanlu001** [comment]
I took this PR and did some modifications (will submit them soon). It's sad that Read the Docs can't display Plotly plots correctly, but we can't forget that the important issue is to attain Plotly 3.0 compatibility. The change in the tuple arithmetic does that, and I also added `require.js` to all notebooks with Plotly plots so at least they show properly in Firefox (not in Chrome), so let's leave like that. Depending on how much time does RTD need to fix these issues, we might need to change our workflow and publish Sphinx artifacts ourselves.

**Comment by Juanlu001** [comment]
Superseded by https://github.com/poliastro/poliastro/pull/399.

**Comment by shreyasbapat** [comment]
Great!😄

**Pull request closed without merging**
