### PR TITLE
Fixing Blog Link

### PR DESCRIPTION
**Pull request by DhruvSondhi**
Hello
This PR aims to fix the wrong Blog Link & redirect to the newer link
Thanks :)

### CODE REVIEW

**Review by astrojuanlu — APPROVED** [review]
Thanks!

**Comment by astrojuanlu** [comment]
...can't merge, it's draft

**Comment by DhruvSondhi** [comment]
@astrojuanlu I think it would be better that @abdulmoiz37 completes this ... if its not a problem 🤔

**Comment by astrojuanlu** [comment]
@abdulmoiz37 was working on the website itself, see https://github.com/poliastro/poliastro.github.io/pull/79

**Comment by DhruvSondhi** [comment]
@astrojuanlu Thanks for merging :)

**Comment by abdulmoiz37** [comment]
Good Work @DhruvSondhi :)

**Pull request merged**
