### PR TITLE
Positions in Hyperbolic Plots

### PR DESCRIPTION
**Pull request by shreyasbapat**
I have added an offset of ``+nu_limit`` to ``nu_values`` . Issue #295  is addressed.

### CODE REVIEW

**Comment by Juanlu001** [comment]
Could you send a couple of screenshots with the before and the after behavior? Like this: https://github.com/poliastro/poliastro/issues/111#issuecomment-355731620

**Comment by Juanlu001** [comment]
Please rebase!

**Comment by shreyasbapat** [comment]
There is a problem in this approach. When we add an offset of "+nu_limit" to "nu_values" the values in "nu_values" become form 0 to 2*nu_limit. Now this goes to a function nu_to_F which in turn computes a logarithmic value, which does not get computed when we give 0 to 2*nu_limit

**Comment by Juanlu001** [comment]
I thought about this carefully. The error is a bit obscure, but probably due to the fact that there are NaN values appearing in the array:

```
In [3]: Time.now() + 1 * u.h
Out[3]: <Time object: scale='utc' format='datetime' value=2018-02-23 11:06:07.789386>

In [4]: (0 * u.h) / (0 * u.h)
/home/juanlu/.miniconda36/envs/poliastro36/lib/python3.6/site-packages/astropy/units/quantity.py:641: RuntimeWarning: invalid value encountered in true_divide
  *arrays, **kwargs)
Out[4]: <Quantity nan>

In [5]: Time.now() + (0 * u.h) / (0 * u.h)
/home/juanlu/.miniconda36/envs/poliastro36/lib/python3.6/site-packages/astropy/units/quantity.py:641: RuntimeWarning: invalid value encountered in true_divide
  *arrays, **kwargs)
---------------------------------------------------------------------------
UnitConversionError                       Traceback (most recent call last)
~/.miniconda36/envs/poliastro36/lib/python3.6/site-packages/astropy/time/core.py in __init__(self, val, val2, format, scale, copy)
   1534                 try:
-> 1535                     val = val.to(u.day)
   1536                     if val2 is not None:

~/.miniconda36/envs/poliastro36/lib/python3.6/site-packages/astropy/units/quantity.py in to(self, unit, equivalencies)
    843         unit = Unit(unit)
--> 844         return self._new_view(self._to_value(unit, equivalencies), unit)
    845 

~/.miniconda36/envs/poliastro36/lib/python3.6/site-packages/astropy/units/quantity.py in _to_value(self, unit, equivalencies)
    815         return self.unit.to(unit, self.view(np.ndarray),
--> 816                             equivalencies=equivalencies)
    817 

~/.miniconda36/envs/poliastro36/lib/python3.6/site-packages/astropy/units/core.py in to(self, other, value, equivalencies)
    978         """
--> 979         return self._get_converter(other, equivalencies=equivalencies)(value)
    980 

~/.miniconda36/envs/poliastro36/lib/python3.6/site-packages/astropy/units/core.py in _get_converter(self, other, equivalencies)
    912 
--> 913             raise exc
    914 

~/.miniconda36/envs/poliastro36/lib/python3.6/site-packages/astropy/units/core.py in _get_converter(self, other, equivalencies)
    898             return self._apply_equivalencies(
--> 899                 self, other, self._normalize_equivalencies(equivalencies))
    900         except UnitsError as exc:

~/.miniconda36/envs/poliastro36/lib/python3.6/site-packages/astropy/units/core.py in _apply_equivalencies(self, unit, other, equivalencies)
    882             "{0} and {1} are not convertible".format(
--> 883                 unit_str, other_str))
    884 

UnitConversionError: '' (dimensionless) and 'd' (time) are not convertible

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
~/.miniconda36/envs/poliastro36/lib/python3.6/site-packages/astropy/time/core.py in __add__(self, other)
   1373             try:
-> 1374                 other = TimeDelta(other)
   1375             except Exception:

~/.miniconda36/envs/poliastro36/lib/python3.6/site-packages/astropy/time/core.py in __init__(self, val, val2, format, scale, copy)
   1540                                      'be used to initiate {0} instances .'
-> 1541                                      .format(self.__class__.__name__))
   1542                 format = 'jd'

ValueError: Only Quantities with Time units can be used to initiate TimeDelta instances .

During handling of the above exception, another exception occurred:

OperandTypeError                          Traceback (most recent call last)
<ipython-input-5-19cbc565acb7> in <module>()
----> 1 Time.now() + (0 * u.h) / (0 * u.h)

~/.miniconda36/envs/poliastro36/lib/python3.6/site-packages/astropy/time/core.py in __add__(self, other)
   1374                 other = TimeDelta(other)
   1375             except Exception:
-> 1376                 raise OperandTypeError(self, other, '+')
   1377 
   1378         # Tdelta + something is dealt with in TimeDelta, so we have

OperandTypeError: Unsupported operand type(s) for +: 'Time' and 'Quantity'
```

The reason why we have NaN values is because we are going above the maximum true anomaly for which the hyperbolic orbit makes sense. Therefore, we have to discard the offset solution (I'm updating the original issue with this information).

The current code "selects a sensible limiting value":

https://github.com/poliastro/poliastro/blob/44dbc6e26f2d0a6b395a910c39c9e8131c8946b2/src/poliastro/twobody/orbit.py#L296-L300

But this value might be lower than the actual anomaly of the point we're plotting!

https://github.com/poliastro/poliastro/issues/111#issuecomment-355746579

Therefore, the sensible value has to be the maximum between `r = 3p` and `r = current_r`. @shreyasbapat could you please try this approach instead?

**Comment by Juanlu001** [comment]
And also, we have to remove the assumtion that the first point is the current point in the plotting code, as I said in #295.

**Comment by shreyasbapat** [comment]
Then what would be the first point? Won't we specify some point?

**Comment by shreyasbapat** [comment]
I will try this approach tonight itself :)

**Comment by Juanlu001** [comment]
On second thought, perhaps we can do something like this:

```
nu_limit = # ...
nu_values = np.linspace(-nu_limit, nu_limit, values)
nu_values = np.insert(nu_values, 0, current_nu)
```

what do you think?

**Comment by shreyasbapat** [comment]
What is this current_nu?

**Comment by Juanlu001** [comment]
The `nu` of the orbit that we're plotting.

**Comment by shreyasbapat** [comment]
Okay! Let's give it a try!

**Comment by shreyasbapat** [comment]
screenshot-2018-2-23 new horizons pluto encounter
Something like this!

**Comment by Juanlu001** [comment]
Nice! Now the plot appears where it is supposed to appear. Still it's not the output that I would like, but I will take care of that in a future pull request :)

This needs at least one test to pass.

**Comment by shreyasbapat** [comment]
I will take care of the test cases!

**Comment by shreyasbapat** [comment]
Yeah! It's not very exact :/

**Comment by Juanlu001** [comment]
According to codecov, this code is not being covered:

https://codecov.io/gh/poliastro/poliastro/compare/36379a98f19dda2e037de6dc2547084450fec93a...0146c12ac973c86116894afad6c550a85f6f7b18

And it makes sense, because for tests to run, the function name has to start with `test_` :)

However, I went to the Travis build and saw that the test names are not there. I will fix that myself on another PR.

**Pull request merged**
