### PR TITLE
[WIP] Address #564: Add range independent nu<->E transformation

### LINKED ISSUE #564: Implicit assumption about range in `nu_to_E`/`E_to_nu`
🐞 **Problem**

The code for transformations between eccentric and true anomaly implicitly assumes that
the input anomaly is in the interval `[-pi, pi]`.

🎯 **Goal**

Provide a more robust formulation that also work for `[0.0, 2 * pi]`.

💡 **Possible solutions**

Use the formulation used by [Orekit](https://github.com/CS-SI/Orekit/blob/develop/src/main/java/org/orekit/orbits/KeplerianOrbit.java#L577) which works in both ranges.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by helgee**
Fixes #564

### CODE REVIEW

**Comment by helgee** [comment]
This is odd. I am getting inconsistent results between PyTest and the REPL. Any hints? My knowledge about Python tooling is a bit rusty.

**Comment by Juanlu001** [comment]
I think you just discovered a bug in that docstring :) You were probably mixing the fast function and the safe function. I think I can't push to your branch, so here is the patch:

```patch
From 9247e4f0ba5b846ce41d2c47ecdd647979403a52 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Juan=20Luis=20Cano=20Rodr=C3=ADguez?= <juanlu001@gmail.com>
Date: Wed, 6 Feb 2019 11:02:14 +0100
Subject: [PATCH 1/2] Fix fast function example

---
 src/poliastro/core/angles.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/poliastro/core/angles.py b/src/poliastro/core/angles.py
index e06749e..4cbd5be 100644
--- a/src/poliastro/core/angles.py
+++ b/src/poliastro/core/angles.py
@@ -406,8 +406,8 @@ def M_to_nu(M, ecc, delta=1e-2):
 
     Examples
     --------
-    >>> import astropy.units as u
-    >>> M_to_nu(30.0 * u.deg, 0.06 * u.one)
+    >>> from numpy import radians, degrees
+    >>> degrees(M_to_nu(radians(30.0), 0.06))
     33.67328493021166
 
     """
-- 
2.17.1

```

**Comment by Juanlu001** [comment]
@jorgepiloto do you want to review this one?

**Comment by Juanlu001** [comment]
Dammit, clicked the wrong button. I will deal with this manually. Thanks @helgee!

**Pull request closed without merging**
