### PR TITLE
Allow propagation to use classical orbital elements

### PR DESCRIPTION
**Pull request by Yash-10**
In reference to #921, this implementation attempts to allow propagators to use classical orbital elements for propagation:

- Implemented on `farnocchia,mikkola,markley,pimienta,gooding,danby` propagators.
- `Orbit.propagate` has been given a keyword argument `classical` (default to `False`) which when set to `True` uses `classical` orbital elements for propagation.

In the test added, the position and velocity vectors returned in both cases (`classical=True` and `classical=False`) do not seem to be in agreement with each other currently. That would certainly need more investigation.

Thanks!!

### CODE REVIEW

**Comment by Yash-10** [comment]
@astrojuanlu Could you please let me know what do you think about this? 

Thanks!!

**Comment by astrojuanlu** [comment]
Hi @Yash-10, sorry for the delay ! Here I am observing the same weird CI failures I saw in #1027. I will open an issue, we'll have to deal with those separately.

**Comment by Yash-10** [comment]
Hello @astrojuanlu, thank you for your reply! Yes, we would have to deal with those CI failures. There was a small unit conversion problem in my earlier commit, which I have also recently changed.

Thanks!!

**Comment by astrojuanlu** [comment]
Hello @Yash-10 ! Are you able to see the build failures and the documentation warnings? For example, on the Read the Docs build I see this:

```
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1098/docs/source/autoapi/poliastro/core/propagation/farnocchia/index.rst:133: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1098/docs/source/autoapi/poliastro/core/propagation/farnocchia/index.rst:134: WARNING: Literal block ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1098/docs/source/autoapi/poliastro/core/propagation/index.rst:102: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/poliastro/checkouts/1098/docs/source/autoapi/poliastro/core/propagation/index.rst:103: WARNING: Literal block ends without a blank line; unexpected unindent.
```

You should not wait for me to say "this needs fixing" 🙃 If the build status is red, you should either fix it or ask for help if you don't know how to.

**Comment by astrojuanlu** [comment]
Thanks! Now that the quality checks were addressed, I observe that some propagation tests give unit errors when disabling numba (the coverage job sets `NUMBA_DISABLE_JIT=1` to actually measure line coverage), for example `test_propagation_cartesian_and_classical_matches`. Could you please have a look?

**Comment by Yash-10** [comment]
Hello @astrojuanlu, I'm sorry for not correcting the build failures that are occuring currently and from now on, I would be more responsible for either asking for help or fixing any failures.

Looking at the codeclimate failure, it seems that Cyclomatic complexity is too high for the propagators implemented in `twobody/propagation.py` ([here](https://codeclimate.com/github/poliastro/poliastro/pull/1098#)). It is most probably due to the code checking if the function expects `classical` or `cartesian` elements. 

Making two separate functions for them might reduce the complexity (and potentially become free from using `*elements` as the argument) but I was wondering whether it would be intelligent to do that since then we would have two separate functions even if their underlying working is very similar.

Could you let me know what would be preferred here?

Thanks!!

**Comment by astrojuanlu** [comment]
Ignore codeclimate for now, we'll decide later :) Focus on the other ones

**Comment by Yash-10** [comment]
I am currently investigating the cause for the unit conversion errors in the absence of numba. It felt like a quick fix but feels like I am missing something trivial. Will get back soon :)

**Comment by astrojuanlu** [comment]
Sure thing @Yash-10 ! 💪🏽

**Comment by Yash-10** [comment]
I was overthinking earlier and tried a bunch of changes. Now the coverage seems to be fine.

The codeclimate failure is probably because the propagator checks for classical and cartesian elements inside the function. Maybe making two separate functions for it can solve that problem (by reducing the complexity). 

Apart from that, two functions give error because it exceeds the max no. of arguments allowed. An initial thought was to harcode `numiter` and `rtol` inside the function to get rid of those extra arguments, but that reduces the users' flexibility, isn't it?

Could you please let me know whether the above is fine or something else is preferred? @astrojuanlu

**Comment by Yash-10** [comment]
I further added some conditions to handle incorrect no. of arguments in the propagator functions. The failing checks (except the codeclimate one) seem to be unrelated, isn't it?

**Comment by Yash-10** [comment]
At the moment, having two separate functions to manage complexity issues in the functions (except `propagate`) might be the solution but for `propagate`, finding a way to reduce its no. of arguments from 6 to 5 is tricky, since we need the additional `classical` argument.

@astrojuanlu Do you have any suggestions?

Thanks!

**Comment by astrojuanlu** [comment]
> The failing checks (except the codeclimate one) seem to be unrelated, isn't it?

Yes! It's an old recurring issue #959

**Review by astrojuanlu — CHANGES_REQUESTED** [review]
Hi @Yash-10 , sorry for the long delay but I am not really convinced by this approach.

On one hand, we have `_classical` and `_coe` propagators, which looks like an unnecessary duplication. I think we should only keep the `_coe` ones, as we were doing after #921 and #1026.

On the other hand, the fact that some propagators now can either accept classical or cartesian elements makes the API and the docstrings more cumbersome, and the implementation more complex.

It is a good attempt at solving the problem, but unfortunately I see a few drawbacks. I appreciate the willingness to put a solution forward 🚀 but for next time, I suggest that we have some discussion in the issue tracker before deciding how to do the work.

At the moment I don't have a specific proposal on how to tackle #921, and unfortunately I will still need a few more days to get up to speed.

**Comment by Yash-10** [comment]
Sorry for the delay in reverting @astrojuanlu, and yes, a discussion beforehand is better. As you had pointed out, the approach surely needs revamping. In the latest approach, some complexity was reduced. This hopefully is a better one but the complexity in `twobody.propagate` still persists. 

It seems that making two separate functions for propagating (in `twobody.propagation`) with classical and cartesian elements, using something like `propagate` and `propagate_classical`, might be a potential cure for the complexity issues.

Could you let me know your thoughts on this?

Thanks!

**Comment by Yash-10** [comment]
There is one idea that could potentially resolve the complexity issues:

Make two separate `propagate` and `propagate_classical` in `twobody.propagation` and handle conditions in the `propagate` method of `Orbit`. This is because cognitive complexity of `Orbit.propagate` (in poliastro's master branch) is not high.

**Comment by Yash-10** [comment]
Just a quick point: \
It turns out that the change from `1e-14` to `1.2e-14` in `test_sampling.py` is a hack to prevent a sampling error that occurs while testing (an issue for the same has also been created to potentially investigate and resolve it).

**Comment by Yash-10** [comment]
**Summarizing the changes made since last reviewed:**
1. The existing `{propagator}_coe` functions are changed such that they return classical orbital elements instead of just returning `nu`. So there are `{propagator}` and `{propagator}_coe` functions in the core propagation section.
2. Twobody propagation section has `{propagator}` and `{propagator}_classical` functions to allow users to be able to use either of them, as per need.
3. `twobody.propagation.propagate` now contains the logic to use classical or cartesian elements based on the `method` user passes in.
4. `twobody.orbit.propagate` uses the twobody propagation to propagate orbits as they were doing earlier.

An equivalently alternative option (if the logic in point 3 above seems to be too complex for a single function) might be:
Make two separate `propagate` and `propagate_classical` functions in `twobody.propagation` and handle conditions in `Orbit.propagate`.

@astrojuanlu Could you let me know your thoughts on this? Additionally, if this PR is merged, it might probably give a head-start to solve similar issues that exist currently, isn't it?

**Comment by Yash-10** [comment]
Hello @astrojuanlu Could you please check the implementation?

Thanks.

**Comment by Yash-10** [comment]
Also, since there are no issues with code complexity, I think there would no need to do (from my earlier comment):

> An equivalent alternative option (if the logic in point 3 above seems to be too complex for a single function) might be:
Make two separate propagate and propagate_classical functions in twobody.propagation and handle conditions in Orbit.propagate.

where point 3 was:

> twobody.propagation.propagate now contains the logic to use classical or cartesian elements based on the method user passes in.

Could you let me know your views @astrojuanlu ?

**Comment by astrojuanlu** [comment]
(Thanks for diligently keeping this branch up to date, I'm catching up now with everything)

**Review by astrojuanlu — CHANGES_REQUESTED** [review]
I am so sorry for being so slow in reviewing this. Unfortunately, I need to be super concentrated to do it properly, and it's something I haven't been able to do in months. At the same time, I think I've made working on this issue too hard, because it's not properly specified (probably because I am not 100 % sure on how to fix it yet).

Please bear with me with a little more of extra patience.

You said

> The existing {propagator}_coe functions are changed such that they return classical orbital elements instead of just returning nu. 

But `coe2rv` returns cartesian elements. Therefore, with this change both `mikkola_coe` and `mikkola` return cartesian elements. Same with all propagators, I think.

`_coe` stands for Classical Orbital Elements, so I'd expect these propagators to either return the true anomaly (current behavior) or all classical elements (unnecessary, in my opinion).

Then you introduced `_classical` methods that actually return cartesian elements as well. Therefore, I don't fully understand where we are going.

**Comment by Yash-10** [comment]
Hello @astrojuanlu I am really sorry for the mess in this PR and thank you so much for the review. I recall that I had initiated this PR without any discussion beforehand but I strongly feel something can be done here!

About this:
> The existing {propagator}_coe functions are changed such that they return classical orbital elements instead of just returning nu.

Sorry for that, I meant that the function now takes classical orbital elements as arguments instead of cartesian elements and at that time, the motivation for doing this was this comment of yours in #921:

>  However, we will need to make `poliastro.twobody.propagation.propagate` smarter now, by adding some sort of mapping that tells whether the function expects classical elements or cartesian elements.

The naming of those functions probably would have confused us. I am not exactly sure whether I interpreted your statement correctly at that time.

`_classical` methods were introduced for the same reason: to be able to take in classical orbital elements as arguments. A separate function was created because the complexity inside a single function was getting too high. If `_classical` methods are not preferred, we could as well handle conditions inside a single function.

If the current implementation is not satisfying (which I suppose since you have requested changes), I would go more deep into the topic and ask questions to be more clear about the bigger objective. If you have any suggestions, please let me know.

Again, thanks for reviewing this PR!!

**Comment by astrojuanlu** [comment]
Since we didn't reach an agreement and there's lots of outdated back and forth in this thread, I think it's better that we close this PR and start over at some other time. Thanks for the work @Yash-10 !

**Pull request closed without merging**
