### PR TITLE
Fixed Link Redirection to Correct NEOs Notebook

### LINKED ISSUE #1160: Fix Link Redirection to NEO's Notebook in Binder
🐞 **Problem**
The Binder repository is giving a `404` error when trying to redirect to the `Using NEO Package` notebook.

💡 **Possible solutions**
Change the redirection link to the point to the correct notebook path in the `index.ipynb` notebook 😄

### PR DESCRIPTION
**Pull request by abdulmoiz37**
This Should Surely Fix #1160 :)

### CODE REVIEW

**Comment by DhruvSondhi** [comment]
This seems to be correct but we have 2 issues to solve before merging this:
1. `py18_test_windows` is failing ... it needs to be solved before the merge
2. The branch in behind the `poliastro/main` branch ... please rebase on the current branch so that the recent changes are incorporated

**Comment by Yash-10** [comment]
Although a rebase is needed, I wonder whether the `TclError` is not related to this PR...

**Comment by abdulmoiz37** [comment]
@DhruvSondhi So Should I Open this PR again with the main branch again?

**Comment by DhruvSondhi** [comment]
No, @abdulmoiz37 you can update this branch through a `rebase` on the updated `main` branch 🤔

**Comment by astrojuanlu** [comment]
@abdulmoiz37 I see that you already rebased - thanks!

**Pull request merged**
