### PR TITLE
Refactor build ephem interpolant

### PR DESCRIPTION
**Pull request by applysomesky**
This is a refactoring done to avoid issues such as #1506 and #1494.
```
def build_ephem_interpolant(body, period, t_span, rtol=1e-5, attractor=Earth)
```
Becomes
```
def build_ephem_interpolant(body, epochs, attractor=Earth)
```
This was done because a too small `t_span` in combination with a too big `rtol` could lead to zero or one epoch point(s), meaning no interpolant could be made, causing errors. This somewhat unclear behaviour is now solved by only giving a `poliastro.util.time_range` generated array of time values directly, together with the `body`. For the user it should be more clear that they input an array of times through which an interpolant will be made.

Furthermore the `poliastro.util.time_range` function had its `periods` argument renamed to `num_values` to reflect the purpose of this value a bit more clear.

### CODE REVIEW

**Comment by applysomesky** [comment]
I see I missed a lot of tests 🙃

**Comment by astrojuanlu** [comment]
Thanks for this PR @applysomesky! I see there are some tricky tests still:

```
E               ValueError: No time format was given, and the input is not unique
```

this is probably a consequence of how `time_range` passes the time values to the `astropy.time.Time` initializer, and this does not work in some cases. For example, here:

```
        j_date = 2454283.0 * u.day
        tof = (test_params["tof"]).to_value(u.s)
    
>       body_epochs = time_range(
            j_date,
            num_values=test_params["ephem_values"],
            end=j_date + test_params["tof"],
        )

```

I'm thinking that maybe you could do `j_date = Time(2454283.0 * u.day, format="jd")` to resolve the ambiguity from the outside.

**Comment by astrojuanlu** [comment]
Indeed:

```python
In [3]: Time(2454283.0 * u.day)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [3], in <module>
----> 1 Time(2454283.0 * u.day)

File ~/Projects/LSF/poliastro/library/.venv/lib/python3.10/site-packages/astropy/time/core.py:1531, in Time.__init__(self, val, val2, format, scale, precision, in_subfmt, out_subfmt, location, copy)
   1529         self._set_scale(scale)
   1530 else:
-> 1531     self._init_from_vals(val, val2, format, scale, copy,
   1532                          precision, in_subfmt, out_subfmt)
   1533     self.SCALES = TIME_TYPES[self.scale]
   1535 if self.location is not None and (self.location.size > 1
   1536                                   and self.location.shape != self.shape):

File ~/Projects/LSF/poliastro/library/.venv/lib/python3.10/site-packages/astropy/time/core.py:384, in TimeBase._init_from_vals(self, val, val2, format, scale, copy, precision, in_subfmt, out_subfmt)
    381 mask, val, val2 = _check_for_masked_and_fill(val, val2)
    383 # Parse / convert input values into internal jd1, jd2 based on format
--> 384 self._time = self._get_time_fmt(val, val2, format, scale,
    385                                 precision, in_subfmt, out_subfmt)
    386 self._format = self._time.name
    388 # Hack from #9969 to allow passing the location value that has been
    389 # collected by the TimeAstropyTime format class up to the Time level.
    390 # TODO: find a nicer way.

File ~/Projects/LSF/poliastro/library/.venv/lib/python3.10/site-packages/astropy/time/core.py:429, in TimeBase._get_time_fmt(self, val, val2, format, scale, precision, in_subfmt, out_subfmt)
    426 elif not (isinstance(format, str)
    427           and format.lower() in self.FORMATS):
    428     if format is None:
--> 429         raise ValueError("No time format was given, and the input is "
    430                          "not unique")
    431     else:
    432         raise ValueError("Format {!r} is not one of the allowed "
    433                          "formats {}".format(format,
    434                                              sorted(self.FORMATS)))

ValueError: No time format was given, and the input is not unique

In [4]: Time(2454283.0 * u.day, format="jd")
Out[4]: <Time object: scale='utc' format='jd' value=2454283.0>

```

**Comment by applysomesky** [comment]
Yeah I noticed (after a bit). 

(At the moment I am not able to run `pytest` with my changes locally)

**Review by astrojuanlu — APPROVED** [review]
Waiting for the CI to pass, but this looks perfect to me 💯

**Review by astrojuanlu — APPROVED** [review]
It was a glitch, all the tests have passed now 😎 Merging!

**Pull request merged**
