### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Nirav-Madhani**
Fixed Binder Demo Link

Original Link was showing error: Error loading poliastro/poliastro/master!

changed master to main.

### CODE REVIEW

**Comment by DhruvSondhi** [comment]
Hello @Nirav-Madhani ... Thank you for this contribution but I am afraid that this has already been fixed in #1123

**Comment by Nirav-Madhani** [comment]
> 
> 
> Hello @Nirav-Madhani ... Thank you for this contribution but I am afraid that this has already been fixed in #1123

Ok then I'll close this one.

**Comment by DhruvSondhi** [comment]
You can try other remaining ones on the #1119 ... 😄

**Comment by Nirav-Madhani** [comment]
Sure.. I Will work on that. 👍

**Pull request closed without merging**
