### PR TITLE
Added OS X testing to Travis CI

### PR DESCRIPTION
**Pull request by Juanlu001**

### CODE REVIEW

**Comment by Juanlu001** [comment]
Closing this PR as Python is not yet available in the OS X environment, see travis-ci/travis-ci#2312.

**Comment by Juanlu001** [comment]
For future reference: .travis.yml can be checked on http://lint.travis-ci.org/

**Comment by Juanlu001** [comment]
Until travis-ci/travis-ci#2312 is fixed, @newlawrence can provide "automated" testing :grin:

**Comment by newlawrence** [comment]
So proud to serve the cause! I'm the smartest of the build-machines 😎

**Pull request closed without merging**
