### PR TITLE
Change `.format` to f-strings

### PR DESCRIPTION
**Pull request by Yash-10**
A slight movement from `.format` to f-strings might take up some less space and look better?

Thanks!

### CODE REVIEW

**Review by jorgepiloto — CHANGES_REQUESTED** [review]
Thank you for this little improvement @Yash-10.

I noticed that you decided to kept the strings being formatted with: `MACRO_STRING.format` such us `ORBIT_NO_FRAME_FORMAT.format(...)`. I guess this is because it it is difficult to modify these macros behavior so they can work with f-strings, making the code not so elegant.

Taking advantage of this, let us also fix the following line in one of the tests:
https://github.com/poliastro/poliastro/blob/bebbf617e0ebfb797ba1c593b8241e4cf0f9c466/tests/tests_twobody/test_orbit.py#L1242

**Comment by Yash-10** [comment]
> I noticed that you decided to kept the strings being formatted with: MACRO_STRING.format such us ORBIT_NO_FRAME_FORMAT.format(...). I guess this is because it it is difficult to modify these macros behavior so they can work with f-strings, making the code not so elegant.

Yeah, I had read that it is sometimes better to stick with the older `.format` in cases like the one you proposed.

> Taking advantage of this, let us also fix the following line in one of the tests:

Thanks for this @jorgepiloto ! I think I addressed your comment..

**Review by jorgepiloto — APPROVED** [review]
Thanks for the changes @Yash-10. Please, squash the commits and this is ready to be merged if @astrojuanlu approves :+1:

**Review by astrojuanlu — APPROVED** [review]

**Comment by astrojuanlu** [comment]
Thanks a lot @Yash-10 !

**Pull request merged**
