### PR TITLE
Support for Azure Pipelines

### PR DESCRIPTION
**Pull request by jains8844**
In reference to #822 

Some changes are required like endpoint, build_url and also triggers.

### CODE REVIEW

**Comment by Juanlu001** [comment]
Thanks @jains8844 for doing this work! This would close #664 and #822.

> Some changes are required like endpoint, build_url and also triggers.

Do we need to do anything from the project side?

**Comment by jains8844** [comment]
> Do we need to do anything from the project side?

Yeah 

1. The `BUILD_URL` will change according to the pipeline you will set up.
2. Same thing to the endpoint.
3. Triggers refer to which branches and which tags to include and exclude and how to trigger the CI.

**Comment by jains8844** [comment]
Also what about the failing tests @Juanlu001 ?

**Comment by Juanlu001** [comment]
Current test results: https://dev.azure.com/jains8844/sample-proj/_build/results?buildId=22&view=results

**Comment by Juanlu001** [comment]
@jains8844 I propose we remove the image tests from Windows and macOS. I proposed it at the beginning but it was a bad idea, I'm sure they're failing because of typography and stuff like that.

**Comment by jains8844** [comment]
Sure sir

**Comment by jains8844** [comment]
All the tests passed :)

**Comment by jains8844** [comment]
I think we should have online tests too for certain platform.
Also regarding the online tests, I ran `pytest -vvv --remote-data=any test_orbit.py::test_from_sbdb`.
This test fails with [this](https://pastebin.com/GvWrST9Y).

**Comment by jains8844** [comment]
Any review for this 😅

**Comment by Juanlu001** [comment]
Sorry @jains8844, I need to find the time to create the project in Azure pipelines. Hopefully today or tomorrow.

**Comment by Juanlu001** [comment]
> Also regarding the online tests, I ran pytest -vvv --remote-data=any test_orbit.py::test_from_sbdb.
This test fails with this.

Hmm can you add them as well? I lost count of how many jobs we have so far, but perhaps it's not an issue if we have more than 10?

**Comment by jains8844** [comment]
Okay sure :)

**Comment by jains8844** [comment]
> > Also regarding the online tests, I ran pytest -vvv --remote-data=any test_orbit.py::test_from_sbdb.
> > This test fails with this.
> 
> Hmm can you add them as well? I lost count of how many jobs we have so far, but perhaps it's not an issue if we have more than 10?

Yeah no issue but one will be pending till one of the other finishes.
Can it be added in py38 test only rather than having a separate test ?

**Comment by astrojuanlu** [comment]
Getting to this ~ _soon_ ~ :muscle: 

Please be ready to rebase

**Comment by jains8844** [comment]
Aye sir

**Comment by astrojuanlu** [comment]
Please rebase!

**Comment by jains8844** [comment]
Done!

**Comment by astrojuanlu** [comment]
Following https://hynek.me/articles/simple-python-azure-pipelines/

**Comment by astrojuanlu** [comment]
Screenshot_2020-03-17 New pipeline - Pipelines

:unamused:

**Comment by astrojuanlu** [comment]
IT'S ALIIIIIIIVEEEEEEEEEEEEEE

**Comment by astrojuanlu** [comment]
I see one test failing on Windows with:

> This probably means that Tcl wasn't installed properly

The one failing on Linux is #861.

...I am merging anyway :smiling_imp: And let's fix them afterwards!

**Comment by astrojuanlu** [comment]
Thanks *a lot* @jains8844! :heart:

**Comment by jains8844** [comment]
That was fast :o

**Pull request merged**
