### PR TITLE
Fixing Binder Links to point towards Main Branch 

### PR DESCRIPTION
**Pull request by DhruvSondhi**
Hello, 
This PR aims to fix the binder repository that currently points to the `master`, changing to updated `main`
Implements #1119 
Thanks :)

### CODE REVIEW

**Comment by jorgepiloto** [comment]
Thank you @DhruvSondhi. This is working again although I noticed that notebooks named "Revisiting Lambert's problem in Python" and "Propagation using Cowell's formulation" can not be opened. The `'` symbol is the reason behind it... May you please also update lines so we can fix all binder stuff in this same pull request?

https://github.com/poliastro/poliastro/blob/56cc3be975fbdc57110286adbbb219533ea58995/index.ipynb#L32

https://github.com/poliastro/poliastro/blob/56cc3be975fbdc57110286adbbb219533ea58995/index.ipynb#L36

**Comment by DhruvSondhi** [comment]
Sure It was also done prior to this but I can do it again :)

**Comment by jorgepiloto** [comment]
Yes, I think we already solved for this some time ago but for some reason it appeared again... Hopefully, this will be the last time fixing those.

**Review by astrojuanlu — APPROVED** [review]
Thanks @DhruvSondhi !

**Pull request merged**
