### PR TITLE
Implemented get_document functionality

### PR DESCRIPTION
**Pull request by asalia-1**
fixes issue #818 

implemented a method for the CZMLExtractor class that returns a czml3.core.Document object from list of packets

### CODE REVIEW

**Comment by Juanlu001** [comment]
Hi @asalia-1, thanks for this pull request! The "quality" check is complaining with this error:

```
flake8 src
src/poliastro/czml/extract_czml.py:495:38: W292 no newline at end of file
```

which is also shown here on GitHub.

Also, the coverage check will fail unless you add a test for the new feature. Something like checking that the result of `get_document` contains the expected list of packets should suffice. For inspiration you can read the rest of the tests of poliastro and czml3, and if you need assistance you can ask us.

**Comment by asalia-1** [comment]
Thanks for the feedback @Juanlu001. I will work on it and let you know if I have questions. Thanks again!

**Comment by Juanlu001** [comment]
Hi @asalia-1! Do you still intend to work on this PR?

**Comment by asalia-1** [comment]
Hi Juan, Sorry I have been out of touch lately. I lost my laptop and it took me a while to a new one back. I apologize for the lack of communication. I would still like to work on this PR. Thanks for checking in with me.

**Comment by Juanlu001** [comment]
Hi @asalia-1! I'm so sorry for your laptop :frowning_face: Don't worry about the delay and get back to this whenever you want.

**Comment by asalia-1** [comment]
Thanks for your patience @Juanlu001 !

**Comment by astrojuanlu** [comment]
Hi @asalia-1! This will now require a rebase, we fixed an issue with the docs in CI.

**Comment by astrojuanlu** [comment]
Superseded by #886. Hope you keep contributing to the project in the future @asalia-1!

**Pull request closed without merging**
