### PR TITLE
Update in Configuration of Pipeline

### PR DESCRIPTION
**Pull request by abdulmoiz37**
@astrojuanlu #1119 can you merge this and Close this Issue ;)

### CODE REVIEW

**Comment by DhruvSondhi** [comment]
This seems to be correct but @astrojuanlu I had this query that the title of the notebook should be `Analysing NEO With Poliastro` instead of `Using NEO's Package` ... Plus this branch is behind the current `poliastro/main` branch ... please rebase on the current `main` to incorporate the new changes 🤔

**Comment by astrojuanlu** [comment]
@DhruvSondhi, the name of the notebook in `index.ipynb` is unrelated to #1119. Please do not introduce confusion.

@abdulmoiz37, @DhruvSondhi  is right about `main` - Please rebase this pull request on top of the `main` branch of `poliastro/poliastro` and then force push, so we have 1 up to date commit.

**Comment by astrojuanlu** [comment]
Well, I changed my mind - it's taking us too much time to fix this, and it's affecting the pipelines, so I'll merge straight away. Thanks @abdulmoiz37 !

**Comment by astrojuanlu** [comment]
Also, in the future I recommend to not call your branches `dev`. You should use 1 branch per feature, and therefore give them meaningful names, and remove them after the pull request is merged. This will simplify your workflow a lot, please bear this into consideration for your future contributions 👍🏽

**Comment by DhruvSondhi** [comment]
Sure @astrojuanlu , Didn't want to add any unnecessary confusion :)

**Comment by abdulmoiz37** [comment]
> Also, in the future I recommend to not call your branches `dev`. You should use 1 branch per feature, and therefore give them meaningful names, and remove them after the pull request is merged. This will simplify your workflow a lot, please bear this into consideration for your future contributions 👍🏽

Sure @astrojuanlu I will not call my branches Dev

**Pull request merged**
