### PR TITLE
Add initial CZML notebook tutorial

### PR DESCRIPTION
**Pull request by Sedictious**
This adds an initial Jupyter notebook tutorial explaining the basic functionality of the CZML extractor

### CODE REVIEW

**Comment by Sedictious** [comment]
@Juanlu001 I think I did it, is this it? 😄

**Comment by Juanlu001** [comment]
That's it! Could you please edit the docs job in the Circle CI conf to `pip install` czml3 as well?

**Comment by Sedictious** [comment]
@Juanlu001 I'm a bit clueless when it comes to conf files. Do I just need to add ``pip install czml3``?

**Comment by Juanlu001** [comment]
In this case:

https://github.com/poliastro/poliastro/blob/b14cb60e1369025213d31deef2640cfcf18ee5d8/.circleci/config.yml#L114

We would need to have `.[dev,cesium]`

**Comment by Juanlu001** [comment]
Thanks a lot!

**Pull request merged**
