### PR TITLE
fix the links #1152

### LINKED ISSUE #1152: Fix links in tutorial
In [this](https://docs.poliastro.space/en/latest/examples/Propagation%20using%20Cowells%20formulation.html#Cowell's-formulation) tutorial, two links are not rendered correctly.

Screenshot from 2021-04-05 13-46-45

Converting those `<a href ...` tags to markdown style links would fix the issue.

### PR DESCRIPTION
**Pull request by niharsalunke**
Hi @Yash-10, creating this pull request after making the required changes. Please ignore my earlier comment.
Fixes #1152 
Thanks.
image

### CODE REVIEW

**Comment by Yash-10** [comment]
Hi @niharsalunke Thanks for making this PR!

Could you convert the links in the markdown format instead of any `<a href ..` tags. This would allow consistency throughout the documentation and `mystnb` allows us to do that.

Also, I was still not able to get the links when I reproduced your fix locally but since you have shared a screenshot, I would take a look.

Thanks!

**Comment by DhruvSondhi** [comment]
Hello @niharsalunke ... I have a suggestion for fixing this ... Instead of making the required `HTML` tag changes, I think making reference for the links would be better ... What I mean by this is can we make a _superscript_ of the links & link those relevant websites to the end of the document? 
Also, I am not in favour of using something like a `class` attribute in the `<a>_</a>` tags

**Comment by DhruvSondhi** [comment]
Another thing that seems to be off is that, Why is `+++` being rendered as it? It is not present in the documentation ... Can you Please confirm the same?

**Comment by astrojuanlu** [comment]
A few things:

- @niharsalunke Thanks for this pull request! Can you explain how this fix works? Or where did you learn about it?
- As the notebook already uses a `<div>` to create an admonition, I am not sure having Markdown syntax inside would work.
- We cannot see the rendered version of this because of https://github.com/poliastro/poliastro/issues/1155

**Comment by Yash-10** [comment]
Hello @astrojuanlu

> As the notebook already uses a \<div> to create an admonition, I am not sure having Markdown syntax inside would work.

Changing links using the markdown syntax does work for me locally
```mystnb
<div class="alert alert-info">For an in-depth exploration of this topic, still to be integrated in poliastro, check out [this Master thesis](https://github.com/Juanlu001/pfc-uc3m)</div>

<div class="alert alert-info">An earlier version of this notebook allowed for more flexibility and interactivity, but was considerably more complex. Future versions of poliastro and plotly might bring back part of that functionality, depending on user feedback. You can still download the older version [here](https://github.com/poliastro/poliastro/blob/0.8.x/docs/source/examples/Propagation%20using%20Cowell's%20formulation.ipynb).</div>
```
Screenshot from 2021-04-06 13-29-04

But I would need to take a look if this is the right approach or needs some standard technique.

Thanks.

**Comment by niharsalunke** [comment]
Hi @Yash-10, I have created another PR. Is this what is expected? I have revised the previous approach (anchor tags). 
The current approach is influenced by https://github.com/poliastro/poliastro/blob/eedc5f1c810b748b7b0bbc719c2147371b0abba3/docs/source/examples/Revisiting%20Lamberts%20problem%20in%20Python.mystnb#L16

@DhruvSondhi, I think you want the links to be embedded with [this](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html?highlight=anchor#links-to-external-web-pages) approach, or maybe [this](https://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html).

@astrojuanlu, I had inspected the HTML version of https://github.com/poliastro/poliastro/blob/eedc5f1c810b748b7b0bbc719c2147371b0abba3/docs/source/examples/Revisiting%20Lamberts%20problem%20in%20Python.mystnb#L16 on the docs page and combined the incomplete knowledge with anchor tags script in https://github.com/poliastro/poliastro/blob/eedc5f1c810b748b7b0bbc719c2147371b0abba3/docs/source/examples/Propagation%20using%20Cowells%20formulation.mystnb#L24 
only to realize later that it was wrong and all the content was being converted to "paragraph" tags.

**Comment by astrojuanlu** [comment]
Thanks for the explanations. Unfortunately, until we fix #1155 we won't be able to merge documentation related pull requests, as we can't validate whether they are right or wrong.

**Comment by Yash-10** [comment]
Hello @astrojuanlu I think #1155 was addressed in #1161 ?

**Comment by astrojuanlu** [comment]
Oops, I can't catch up with this volume of notifications 😉 Thanks @Yash-10 !

**Comment by niharsalunke** [comment]
Hi @astrojuanlu, sure. Thanks a Lot! 😄

**Review by astrojuanlu — CHANGES_REQUESTED** [review]
✔️ I just checked that the links now render correctly
❌ You modified some files not related to the fix. Please restore them, squash all the commits into one, and rebase this pull request on top of the `main` branch. Ask for help in our chat if you need assistance.

**Comment by niharsalunke** [comment]
Created PR #1163 with the required corrections.
Thanks.

**Comment by astrojuanlu** [comment]
Well, my recommendation going forward is that you learn how to rebase and squash - but it's fine :)

**Comment by DhruvSondhi** [comment]
@niharsalunke Why was this PR closed?
Updates for the relevant code changes can be done in this PR itself by pushing more commits for the same

**Pull request closed without merging**
