### PR TITLE
Fixed the binder notebook links

### PR DESCRIPTION
**Pull request by DhruvSondhi**
Hello, This PR fixes the broken binder links to the modified notebooks 😄

### CODE REVIEW

**Comment by DhruvSondhi** [comment]
Triggering pipeline for an unrelated issue :)

**Comment by astrojuanlu** [comment]
Yes, this fixes the links. But does it fix _opening_ the notebooks in Binder? I tried it and I think it doesn't. Please confirm.

**Comment by DhruvSondhi** [comment]
I can confirm that the notebooks are not even being recognised by *binder* & hence they are not even opening. Also, checking the URL of the notebooks in notebooks suggest that it is still finding the notebooks in `.md` format & it is not updating the changed references. Very well could be the problem with `Jupytext` extension (nice catch 😉) 🤔

**Comment by astrojuanlu** [comment]
Closing in favor of #1082.

**Pull request closed without merging**
