### PR TITLE
Alternative bodies implementation

### PR DESCRIPTION
**Pull request by Juanlu001**
This structure is a bit contrived but allows for more flexibility. @anhiga I think this would help in adding rotating elements for #215, but I admit it is strange to use the classes like that. Please review it and merge it if you think it is going to be useful.

### CODE REVIEW

**Comment by Juanlu001** [comment]
To clarify: the `Body` class remains for the user to create generic bodies, inherit it, or whatever. The rest of the classes are all private so only the specific instances can be seen from the outside.

**Comment by Juanlu001** [comment]
AppVeyor got stuck for 20 minutes... Restarting.

**Comment by Juanlu001** [comment]
And also I approved the repeated code warnings in Codeclimate because I prefer explicit, repeated code in this case (and also because it annoys me)

**Comment by Juanlu001** [comment]
http://status.appveyor.com/incidents/2tjbzx1mtnz8

I already subscribed.

**Comment by anhiga** [comment]
I'm looking for another alternatives, but it appears to be the only way to have rotating elements in `bodies` module...
Also, although code could be a little contrived, it is easy to read it and understand it.

**Comment by anhiga** [comment]
The only other approach I can think of right now is working with lambdas, so there is no need of initializing `T` and `d` until we use them. Maybe something like this:
```Python
Mercury = Body.from_parameters(Sun, k=constants.GM_mercury, name="Mercury",
symbol=u"\u263F", R=constants.R_mercury, ra=lambda T, d: 281.01 - 0.033 * T,
dec=lambda T, d: 61.45 - 0.005 * T, W=lambda T, d: 329.548 + 6.1385025 * d)

Mercury.ra(0, 30)
Out: 281.01
```

Or we could have a dictionary of lambdas:
```Python
bodies_orientations = {
    "Mercury": {
        "ra": lambda T, d: 281.01 - 0.033 * T,
        "dec": lambda T, d: 61.45 - 0.005 * T,
        "W": lambda T, d: 329.548 + 6.1385025 * d
    },
```
that could be inside `bodies`, or even inside `constants`.

**Comment by Juanlu001** [comment]
Have you tried the lambdas approach? Because I am not sure if Python will
bound a `self` argument to them. The dictionary of lambdas can work but how
are you doing it with Jupiter for example?

**Comment by anhiga** [comment]
I have tried implementing it, and it works (apparently), but I've never seen lambdas been using like this (I'm quite new to Python, there are probably many things I haven't seen) so I'm not sure if would be a good idea...

**Comment by anhiga** [comment]
Despite of my comments, the lambdas solution would be probably a more confusing solution that the one you provided @Juanlu001, so there isn't another idea, I think we could merge this.

**Comment by Juanlu001** [comment]
We checked locally the lambdas way for complex bodies and it's quite messy. We're going this route.

**Pull request merged**
