### PR TITLE
Add fixtures to test in test_orbit

### PR DESCRIPTION
**Pull request by shreyasbapat**

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Sure! Will do so in an hour or so.

**Comment by shreyasbapat** [comment]
@Juanlu001  Appveyor is failing without even running and no logs!

**Comment by shreyasbapat** [comment]
Is it because there is a merge conflict? And why is there a merge conflict anyways?

**Comment by Juanlu001** [comment]
Because now the code is Black™ ;)

On 26 Dec 2018 7:03 pm, "Shreyas Bapat" <notifications@github.com> wrote:

Is it because there is a merge conflict? And why is there a merge conflict
anyways?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/poliastro/poliastro/pull/508#issuecomment-450002241>,
or mute the thread

**Comment by shreyasbapat** [comment]
@Juanlu001  is it fine now?

**Comment by shreyasbapat** [comment]
Rebased this too!

**Comment by shreyasbapat** [comment]
This happened due to some issue in my internet. I have rebased this again.

**Comment by Juanlu001** [comment]
Sorry, perhaps I wasn't clear enough when I reviewed: I would only use a fixture for the hyperbolic orbit, because I find the fixture for the dummy data more confusing than just putting the variables in every test. Too bad we are only using that hyperbolic orbit in one place...

**Comment by Juanlu001** [comment]
Leave only one fixture

On 27 Dec 2018 10:25 pm, "Shreyas Bapat" <notifications@github.com> wrote:

So, should I put that fixture or we leave it like it is?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/poliastro/poliastro/pull/508#issuecomment-450233894>,
or mute the thread

**Comment by shreyasbapat** [comment]
Done!

**Comment by Juanlu001** [comment]
Thanks again! :grin:

**Pull request merged**
