### PR TITLE
Added recursive series Kepler solver for elliptical orbits

### PR DESCRIPTION
**Pull request by JackCrusoe47**
- Added the series solution approximation for elliptical orbits.  
- Small correction to Danby code. Corrected nu to M for circular orbits as M = nu @ e=0

Currently, I only included the manual series solution, where the user provides the order of recursion (instead of tolerance).

Later, I can implement a hybrid variant that uses a lookup table to select appropriate order for a mean anomaly and eccentricity and then uses the initial guess for a Newton-Raphson. Here, the user will be able to specify a tolerance, and hopefully, the table provides an order of recursion that overall reduce the cost of computing the solution. I am currently having trouble with fast lookup.

Hope I didn't mess anything up with the pull request. I have never worked with Github.

Cheers

### CODE REVIEW

**Review by astrojuanlu — CHANGES_REQUESTED** [review]
Amazing @JackCrusoe47 ! That's what I call "from zero to hero" 😃 Good use of GitHub, nothing to worry about there.

I have a few minor requests:

- Could you rename the module and function names to `all_lowercase` instead of `camelCase`? to keep consistency
- Could you add your method here

https://github.com/poliastro/poliastro/blob/9797eb079d7ce86b39aaef379b750d88c3135ce2/src/poliastro/twobody/propagation.py#L488-L497

so it gets tested automatically?

**Comment by JackCrusoe47** [comment]
Thank you @astrojuanlu. 

of course, I'll do the corrections right away. I also saw that two automatic tests are failing. Is it related to not adding my method in the tests, or would I need to modify anything further?

The tests that fail are:

- codecov/patch
- codecov/project

**Comment by Yash-10** [comment]
Wow! This seems to be a great addition. As the paper states,

> Fast approximation of closest approach distance for co-planar orbits.

this approach could also be a good approach to check out for the satellite collision event #1350, isn't it?

**Comment by JackCrusoe47** [comment]
@Yash-10 Well my idea was to use the recursive series (not more than 3-recursions) as a fast initial guess pass over the domain, to get a rough estimate on solution space. Then use this information to target possible collision regions with an accurate algorithm. Unfortunately, besides mentioning this, I really didn't experiment with this in my paper.

**Comment by JackCrusoe47** [comment]
P.s. I apologize in advance for the state of my commits. I still have not figured a way to edit and test code directly, and still couldn't find the option to roll back commits in Github individually.

**Review by astrojuanlu — COMMENTED** [review]
5 tests have failed:

```
FAILED tests/tests_twobody/test_propagation.py::test_elliptic_near_parabolic[recseries-0.9]
FAILED tests/tests_twobody/test_propagation.py::test_elliptic_near_parabolic[recseries-0.99]
FAILED tests/tests_twobody/test_propagation.py::test_elliptic_near_parabolic[recseries-0.999]
FAILED tests/tests_twobody/test_propagation.py::test_elliptic_near_parabolic[recseries-0.9999]
FAILED tests/tests_twobody/test_propagation.py::test_elliptic_near_parabolic[recseries-0.99999]
```

which means that, with eccentricities of 0.9 and higher, the method loses a bit of accuracy.

I assume this is how the method works, so I'll assist you in relaxing the tolerance for the tests without affecting the other methods.

**Comment by JackCrusoe47** [comment]
> 5 tests have failed:
> 
> ```
> FAILED tests/tests_twobody/test_propagation.py::test_elliptic_near_parabolic[recseries-0.9]
> FAILED tests/tests_twobody/test_propagation.py::test_elliptic_near_parabolic[recseries-0.99]
> FAILED tests/tests_twobody/test_propagation.py::test_elliptic_near_parabolic[recseries-0.999]
> FAILED tests/tests_twobody/test_propagation.py::test_elliptic_near_parabolic[recseries-0.9999]
> FAILED tests/tests_twobody/test_propagation.py::test_elliptic_near_parabolic[recseries-0.99999]
> ```
> 
> which means that, with eccentricities of 0.9 and higher, the method loses a bit of accuracy.
> 
> I assume this is how the method works, so I'll assist you in relaxing the tolerance for the tests without affecting the other methods.

Unfortunately yes. The rate of convergence of the method drops to zero as the eccentricity becomes close to 1. In theory, it should work for cases up to 0.99 with a high enough order (say 20-30 for 0.99 for example). But for now the function I use to convert accuracy to order probably is underpredicting the order for 0.9 and 0.99.

**Comment by JackCrusoe47** [comment]
Maybe I can add an appropriate function to scale order with rtol and eccentricity. It won't probably fix the case of 0.999 and 0.9999, but until 0.99 I think I can make a good prediction.

**Comment by JackCrusoe47** [comment]
All cases more or less should work now. 

Now the recseries( ) solver can be called in the following two ways:
- (rf,vf) = recseries(k, r0, v0, tof, method='order', order=12)   # use a fixed 12th order recursive series
- (rf,vf) = recseries(k, r0, v0, tof, method='rtol', rtol=1e-8)      # recurse until a tolerance of 1e-8

This works the same for recseries_coe( )

**Review by astrojuanlu — APPROVED** [review]
Looks good to me! Will merge when the tests pass 💪🏼

**Comment by JackCrusoe47** [comment]
Perfect. Thank you.

**Comment by astrojuanlu** [comment]
A small coverage difference is not worth blocking this PR 😉

**Comment by astrojuanlu** [comment]
Congratulations @JackCrusoe47 on your first contribution to poliastro! 🎉

**Comment by JackCrusoe47** [comment]
Thank you @astrojuanlu for merging my commits 🚀. I am eager to see its use by the community. 😄

**Pull request merged**
