### PR TITLE
OrbitPlotter now implements show()

### PR DESCRIPTION
**Pull request by shreyasbapat**
Issue #315  Addressed

### CODE REVIEW

**Comment by shreyasbapat** [comment]
@Juanlu001  Please Review :)

**Comment by Juanlu001** [comment]
The code looks good, but I have a problem with this: if you use it, the plot shows twice.

screenshot-2018-3-9 jupyterlab

The issue is probably tricky to fix, since it involves the display mechanism of Jupyter, which is not consistent. Please make sure to try out the changes that you push so you find this kind of problems earlier.

**Comment by Juanlu001** [comment]
The more I find these issues, the more I think we should use Plotly also for 2D plots. However, I don't feel OK dropping the matplotlib interface, because probably it will produce better static plots. This means that we should refactor the whole plotting module in a way that lets you select "backends", and start with two: an interactive backend using Plotly for the notebook (2D and 3D) and a "static" backend that works using matplotlib and only 2D. I added a new issue for this (https://github.com/poliastro/poliastro/issues/338), so please @shreyasbapat think about it, edit your proposal accordingly and let's defer this PR for a moment when we have a clear plan.

**Comment by shreyasbapat** [comment]
Oh! Well I thought we just have to show what we are getting. Okay! I got your point. Basically, now I got the point what you suggested. I will work on it. Thanks a lot. I think this PR can be changed after we refactor our modules as it will be useful to reuse the frame. So I am not closing it Is it fine @Juanlu001 ?

**Comment by Juanlu001** [comment]
Agreed!

**Comment by shreyasbapat** [comment]
Now, should we try to attempt this?

**Comment by Juanlu001** [comment]
I think the aspect ratio issues shown here are much more important https://github.com/poliastro/poliastro/issues/345

**Comment by Juanlu001** [comment]
I closed #315, so I think the best thing is to close this and open a new PR for #338. Is that okay?

**Comment by shreyasbapat** [comment]
True!

**Comment by shreyasbapat** [comment]
Closing this!

**Pull request closed without merging**
