### PR TITLE
Add release.yml workflow

### LINKED ISSUE #1416: Automate PyPI upload and GitHub release
Now I run these steps manually and they could as well be automatic.

### PR DESCRIPTION
**Pull request by jorgepiloto**
Resolves #1416.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
We discussed in the weekly community meetings that notifying from the completion of the workflow in CircleCI might be too complex. So @jorgepiloto will start by making the release procedure work from CircleCI, and if it's too cumbersome we'll port everything to GitHub Actions.

**Comment by jorgepiloto** [comment]
Retaking this 🚀

**Comment by jorgepiloto** [comment]
Debugging this. Let's see if the release workflow gets executed. It does not contain any release logic for the moment.

**Comment by jorgepiloto** [comment]
Just realized that I need to test this in a branch in the current repository.

**Pull request closed without merging**
